import { chromium } from '/home/mgw/src/podium/node_modules/playwright/index.mjs'
import { readFileSync, writeFileSync } from 'node:fs'
const O='http://127.0.0.1:20328',P='p3112-oc-continuity-r18',C='/tmp/pod-3112-oc-continuity-r18/dummy-repo/.worktrees/issue-1-r18-continuity',seed=process.env.R18_SEED!,base='/tmp/pod-3112-oc-continuity-r18',epic='bc0263ccf49d499f60988c297c60554b4217a6b6'
const mono=()=>performance.now(),wall=()=>new Date().toISOString(),sleep=(n:number)=>new Promise(r=>setTimeout(r,n))
const lr=await fetch(O+'/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:P})}),ck=(lr.headers.get('set-cookie')||'').split(';')[0],[cn,cv]=ck.split('=')
if(!ck)throw Error('no auth cookie')
const q=async(p:string,b:any={})=>(await fetch(O+'/trpc/'+p+'?input='+encodeURIComponent(JSON.stringify(b)),{headers:{cookie:ck}})).json() as any
const m=async(p:string,b:any)=>(await fetch(O+'/trpc/'+p,{method:'POST',headers:{cookie:ck,'content-type':'application/json'},body:JSON.stringify(b)})).json() as any
const list=async()=>(await q('sessions.list')).result?.data||[],stat=async(s:string)=>(await q('sessions.status',{ref:s})).result?.data||null,read=async(s:string)=>(await q('sessions.read',{sessionId:s,turns:500})).result?.data||{}
const waitRow=async(s:string,p:(x:any)=>boolean,ms=60000)=>{const t=mono(),samples=[] as any[];while(mono()-t<ms){const row=(await list()).find((x:any)=>x.sessionId===s),st=await stat(s);samples.push({at:wall(),ms:mono()-t,row,status:st});if(row&&p({...row,phase:st?.phase}))return {row,st,samples,ms:mono()-t};await sleep(250)};return {row:null,st:null,samples,ms:null}}
const waitReply=async(s:string,n:string,ms=120000)=>{const t=mono();while(mono()-t<ms){const x=await read(s),items=x.items||[];if(items.filter((i:any)=>i.role==='assistant'&&String(i.text||'').includes(n)).length===1)return {ms:mono()-t,read:x};await sleep(250)};return {ms:null,read:await read(s)}}
const rowIdentity=(r:any)=>({sessionId:r?.sessionId,createdAt:r?.createdAt,status:r?.status,driverId:r?.driverId,requestedDriverId:r?.requestedDriverId??null,driverFamily:r?.driverFamily,accountId:r?.accountId,resume:r?.resume??null,providerSessionId:r?.providerSessionId??null,conversationId:r?.conversationId??null,providerPid:r?.providerPid??r?.pid??null,cwd:r?.cwd})
const browser=await chromium.launch({executablePath:'/home/mgw/.cache/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']})
const ctx=await browser.newContext({viewport:{width:1360,height:880}});await ctx.addCookies([{name:cn,value:cv,url:O,httpOnly:true,sameSite:'Lax'}]);const page=await ctx.newPage(),creates:any[]=[];page.on('request',r=>{if(r.url().includes('/trpc/sessions.create'))creates.push({at:wall(),body:r.postData()})})
const out:any={at:wall(),issue:'POD-3112',kind:'r18-opencode-continuity',journeyId:'opencode-paired-final-tip',epicPin:epic,instance:P,ports:[20328,47344,47345],providerPrompts:0}
let sid=''
const usableViews=async()=>{const n=page.locator('[data-testid="mode-native"]'),c=page.locator('[data-testid="mode-chat"]');await n.waitFor({state:'visible',timeout:30000});await n.click();const na=await n.getAttribute('aria-selected');await c.click();const ca=await c.getAttribute('aria-selected');return {native:na==='true',chat:ca==='true'}}
try{
 const before=new Set((await list()).map((x:any)=>x.sessionId));await page.goto(O+'/?e2e=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!document.querySelector('.app-loading'),undefined,{timeout:90000});const d=page.getByRole('button',{name:/^Dismiss$/i}).first();if(await d.isVisible().catch(()=>false))await d.click();await page.getByText('r18 continuity',{exact:true}).click({timeout:30000});const np=page.locator('button[aria-label="New panel"]:visible').first();await np.click();await page.getByRole('menuitem',{name:/New OpenCode/i}).first().click()
 let row:any;for(let i=0;i<160;i++){row=(await list()).find((x:any)=>!before.has(x.sessionId)&&x.cwd===C);if(row?.driverId)break;await sleep(250)};if(row?.driverId!=='opencode-server'||row?.driverFamily!=='server'||!String(row?.accountId||'').startsWith('native:opencode'))throw Error('REFUSED identity '+JSON.stringify(row));sid=row.sessionId;const native=page.locator('[data-testid="mode-native"]');await native.waitFor({state:'visible',timeout:30000});if(await native.getAttribute('aria-selected')!=='true')throw Error('REFUSED not Native-first');await page.waitForFunction(()=>!!(window as any).__podium,undefined,{timeout:60000});let screen='';for(let i=0;i<240;i++){screen=await page.evaluate(()=>(window as any).__podium?.screenText()||'');if(screen.length>100&&/opencode/i.test(screen)&&!/not logged in|sign in required/i.test(screen))break;await sleep(250)};if(screen.length<100)throw Error('REFUSED CLI unavailable')
 out.launch={createRequests:creates,identity:rowIdentity(row),nativeFirst:true,screenLength:screen.length,rawList:await list(),rawRead:await read(sid)}
 const code='R18-'+Date.now().toString(36).toUpperCase(),nonce='P3112-R18-SEED-'+Date.now().toString(36).toUpperCase(),prompt=`Remember the codeword ${code}. Reply with exactly ${nonce}. Do not use tools.`;const t=mono(),w=wall(),beforeScreen=screen;const ta=page.locator('.xterm-helper-textarea:visible').last();await ta.focus();await page.keyboard.type(prompt,{delay:1});await page.keyboard.press('Enter');out.providerPrompts++;let working=null as number|null,growth=null as number|null;for(let i=0;i<480;i++){const [st,scr]=await Promise.all([stat(sid),page.evaluate(()=>(window as any).__podium?.screenText()||'')]),ms=mono()-t;if(working===null&&st?.phase==='working')working=ms;if(growth===null&&scr!==beforeScreen)growth=ms;if(working!==null&&growth!==null)break;await sleep(250)};const reply=await waitReply(sid,nonce);const seeded=(reply.read.items||[]),uc=seeded.filter((x:any)=>x.role==='user'&&String(x.text||'').includes(nonce)).length,ac=seeded.filter((x:any)=>x.role==='assistant'&&String(x.text||'').includes(nonce)).length;await page.locator('[data-testid="mode-chat"]').click();const chat=await page.locator('[data-testid="chat-surface"]').innerText();out.seed={at:w,codeword:code,nonce,workingMs:working,growthMs:growth,replyMs:reply.ms,userCount:uc,assistantCount:ac,chatOccurrences:chat.split(nonce).length-1,rawRead:reply.read};if(working===null||growth===null||reply.ms===null||uc!==1||ac!==1)throw Error('seed control failed')
 out.beforeRestart={at:wall(),identity:rowIdentity((await list()).find((x:any)=>x.sessionId===sid)),status:await stat(sid),views:await usableViews(),rawList:await list(),rawRead:await read(sid),daemonPid:Number(readFileSync(base+'/daemon.pid','utf8'))};writeFileSync(base+'/restart-ready',JSON.stringify({sid,at:wall()})+'\n');while(!await Bun.file(base+'/restart-done').exists())await sleep(250);const restart=JSON.parse(readFileSync(base+'/restart-done','utf8'))
 const adopted=await waitRow(sid,x=>x.status==='live',90000),afterRow=adopted.row;await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!document.querySelector('.app-loading'),undefined,{timeout:90000});await page.getByText('r18 continuity',{exact:true}).click({timeout:30000});const viewsA=await usableViews();out.a7a={restart,adoptMs:adopted.ms,before:out.beforeRestart.identity,after:rowIdentity(afterRow),sameSession:afterRow?.sessionId===sid,sameCreatedAt:afterRow?.createdAt===row.createdAt,sameResume:JSON.stringify(afterRow?.resume??null)===JSON.stringify(row?.resume??null),views:viewsA,rawList:await list(),rawRead:await read(sid)}
 await native.click();const r1='P3112-R18-A7A-'+Date.now().toString(36).toUpperCase(),p1=`What codeword did I ask you to remember? Reply with exactly ${code} ${r1}.`;await ta.focus();await page.keyboard.type(p1,{delay:1});await page.keyboard.press('Enter');out.providerPrompts++;const rr1=await waitReply(sid,r1);out.a7a.recall={nonce:r1,ms:rr1.ms,remembered:(rr1.read.items||[]).some((x:any)=>x.role==='assistant'&&String(x.text||'').includes(code)),rawRead:rr1.read};out.a7a.verdict=restart.oldPid!==restart.newPid&&out.a7a.sameSession&&out.a7a.sameCreatedAt&&out.a7a.sameResume&&viewsA.native&&viewsA.chat&&out.a7a.recall.remembered?'PASS':'FAIL';writeFileSync(base+'/a7a.json',JSON.stringify(out,null,2)+'\n');if(out.a7a.verdict!=='PASS')throw Error('A7a control failed')
 const idle=await waitRow(sid,x=>x.phase==='idle',60000);const preH=(await list()).find((x:any)=>x.sessionId===sid);const hAt=wall(),h=await m('sessions.hibernate',{sessionId:sid}),park=await waitRow(sid,x=>x.status==='hibernated',90000),parkRow=park.row;const rezAt=wall(),rz=await m('sessions.resurrect',{sessionId:sid}),live=await waitRow(sid,x=>x.status==='live',120000),liveRow=live.row
 await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!document.querySelector('.app-loading'),undefined,{timeout:90000});await page.getByText('r18 continuity',{exact:true}).click({timeout:30000});const viewsB=await usableViews();const r2='P3112-R18-A7B-'+Date.now().toString(36).toUpperCase(),p2=`Recall the original codeword. Reply with exactly ${code} ${r2}.`;await native.click();await ta.focus();await page.keyboard.type(p2,{delay:1});await page.keyboard.press('Enter');out.providerPrompts++;const rr2=await waitReply(sid,r2);const finalRow=(await list()).find((x:any)=>x.sessionId===sid);out.a7b={idle,hibernateAt:hAt,hibernate:h,parkMs:park.ms,parkIdentity:rowIdentity(parkRow),resurrectAt:rezAt,resurrect:rz,liveMs:live.ms,preIdentity:rowIdentity(preH),postIdentity:rowIdentity(liveRow),finalIdentity:rowIdentity(finalRow),sameSession:finalRow?.sessionId===sid,sameCreatedAt:finalRow?.createdAt===row.createdAt,sameResume:JSON.stringify(finalRow?.resume??null)===JSON.stringify(row?.resume??null),views:viewsB,recall:{nonce:r2,ms:rr2.ms,remembered:(rr2.read.items||[]).some((x:any)=>x.role==='assistant'&&String(x.text||'').includes(code)),rawRead:rr2.read},rawList:await list(),rawRead:await read(sid)};out.a7b.verdict=parkRow?.status==='hibernated'&&out.a7b.sameSession&&out.a7b.sameCreatedAt&&out.a7b.sameResume&&viewsB.native&&viewsB.chat&&out.a7b.recall.remembered?'PASS':'FAIL';out.verdict=out.a7b.verdict
 await page.screenshot({path:base+'/continuity.png',fullPage:true})
}catch(e){out.verdict='REFUSED';out.reason=String(e)}finally{out.finishedAt=wall();writeFileSync(base+'/r18-reading.json',JSON.stringify(out,null,2)+'\n');await browser.close().catch(()=>{})};console.log(JSON.stringify({verdict:out.verdict,sid,a7a:out.a7a?.verdict,a7b:out.a7b?.verdict,reason:out.reason},null,2))
