import { chromium } from 'playwright'
import { existsSync, readFileSync, readlinkSync, realpathSync, writeFileSync } from 'node:fs'
import { isAbsolute, join, relative } from 'node:path'
import { instanceStateDir } from '@podium/runtime/instance'
const required=(name:string)=>{const value=process.env[name];if(!value)throw Error(`${name} is required`);return value}
for(const key of ['R18_HOME','PODIUM_STATE_DIR','ABDUCO_SOCKET_DIR','PODIUM_RUNTIME_DRIVER'])if(process.env[key]!==undefined)throw Error(`REFUSED rig-authored ${key} override`)
const parentHome=readFileSync(`/proc/${process.ppid}/environ`,'utf8').split('\0').find(value=>value.startsWith('HOME='))?.slice(5)
if(!process.env.HOME||parentHome!==process.env.HOME)throw Error('REFUSED rig-authored HOME override')
const positivePort=(name:string)=>{const value=Number(required(name));if(!Number.isInteger(value)||value<=0)throw Error(`${name} must be a positive integer`);return value}
const port=positivePort('R18_PORT'),hookPort=positivePort('R18_HOOK_PORT'),relayPort=positivePort('R18_RELAY_PORT')
const P=required('R18_INSTANCE')
if(P==='default'||P==='p3112-oc-continuity-r18')throw Error(`REFUSED unsafe or prior R18_INSTANCE ${P}`)
const ports=[port,hookPort,relayPort]
if(new Set(ports).size!==3)throw Error('REFUSED R18 ports must be distinct')
const forbiddenPorts=new Set([19797,32090,20328,47344,47345])
if(ports.some(value=>forbiddenPorts.has(value)))throw Error(`REFUSED unsafe or prior R18 port ${ports.find(value=>forbiddenPorts.has(value))}`)
const requestedBase=required('R18_BASE'),requestedCwd=required('R18_CWD')
const base=realpathSync(requestedBase),C=realpathSync(requestedCwd)
if(base==='/tmp/pod-3112-oc-continuity-r18'||!/^\/tmp\/pod-3112-[^/]+$/.test(base))throw Error(`REFUSED unsafe or prior R18_BASE ${base}`)
const cwdRelative=relative(base,C)
if(!cwdRelative||cwdRelative.startsWith('..')||isAbsolute(cwdRelative))throw Error(`REFUSED R18_CWD must be strictly beneath R18_BASE: ${C}`)
const O=`http://127.0.0.1:${port}`,epic=required('R18_EPIC_PIN'),workspace=required('R18_WORKSPACE')
const mono=()=>performance.now(),wall=()=>new Date().toISOString(),sleep=(n:number)=>new Promise(r=>setTimeout(r,n))
const journalPath=(sid:string)=>join(instanceStateDir(P),'opencode-servers',`${encodeURIComponent(sid)}.json`),journalSafe=(sid:string)=>{if(!existsSync(journalPath(sid)))return null;const raw=JSON.parse(readFileSync(journalPath(sid),'utf8')),safe={opencodeSessionId:raw.opencodeSessionId,process:{key:raw.process?.key,pid:raw.process?.pid},workdir:raw.workdir,seq:raw.seq,turnEpoch:raw.turnEpoch,bindingVersion:raw.bindingVersion};if(!safe.opencodeSessionId||!safe.process.key||!Number.isInteger(safe.process.pid)||safe.process.pid<=0||!safe.workdir||!Number.isInteger(safe.seq)||safe.seq<0||!Number.isInteger(safe.turnEpoch)||safe.turnEpoch<0||!Number.isInteger(safe.bindingVersion)||safe.bindingVersion<=0)throw Error('REFUSED incomplete safe journal fields');return safe}
const processProof=(pid:number)=>{let live=false,cwd:string|null=null,instance=false;try{process.kill(pid,0);live=true;cwd=readlinkSync(`/proc/${pid}/cwd`);instance=readFileSync(`/proc/${pid}/environ`,'utf8').split('\0').includes(`PODIUM_INSTANCE=${P}`)}catch{}return {pid,live,cwd,instance,exact:live&&cwd===C&&instance}}
const lr=await fetch(O+'/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:P})}),ck=(lr.headers.get('set-cookie')||'').split(';')[0],[cn,cv]=ck.split('=')
if(!ck)throw Error('no auth cookie')
const q=async(p:string,b:any={})=>(await fetch(O+'/trpc/'+p+'?input='+encodeURIComponent(JSON.stringify(b)),{headers:{cookie:ck}})).json() as any
const m=async(p:string,b:any)=>(await fetch(O+'/trpc/'+p,{method:'POST',headers:{cookie:ck,'content-type':'application/json'},body:JSON.stringify(b)})).json() as any
const list=async()=>(await q('sessions.list')).result?.data||[],stat=async(s:string)=>(await q('sessions.status',{ref:s})).result?.data||null,read=async(s:string)=>(await q('sessions.read',{sessionId:s,turns:500})).result?.data||{}
const waitRow=async(s:string,p:(x:any)=>boolean,ms=60000)=>{const t=mono(),samples=[] as any[];while(mono()-t<ms){const row=(await list()).find((x:any)=>x.sessionId===s),st=await stat(s);samples.push({at:wall(),ms:mono()-t,row,status:st});if(row&&p({...row,phase:st?.phase}))return {row,st,samples,ms:mono()-t};await sleep(250)};return {row:null,st:null,samples,ms:null}}
const waitReply=async(s:string,n:string,ms=120000)=>{const t=mono();while(mono()-t<ms){const x=await read(s),items=x.items||[];if(items.filter((i:any)=>i.role==='assistant'&&String(i.text||'').includes(n)).length===1)return {ms:mono()-t,read:x};await sleep(250)};return {ms:null,read:await read(s)}}
const rowIdentity=(r:any)=>({sessionId:r?.sessionId,createdAt:r?.createdAt,status:r?.status,driverId:r?.driverId,requestedDriverId:r?.requestedDriverId??null,driverFamily:r?.driverFamily,accountId:r?.accountId,resume:r?.resume??null,providerSessionId:r?.providerSessionId??null,conversationId:r?.conversationId??null,providerPid:r?.providerPid??r?.pid??null,cwd:r?.cwd})
const browser=await chromium.launch({executablePath:'/home/mgw/.cache/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-linux64/chrome-headless-shell',env:{...process.env,LD_LIBRARY_PATH:'/tmp/pod-3112-browser-libs/extracted/usr/lib/x86_64-linux-gnu'},args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']})
const ctx=await browser.newContext({viewport:{width:1360,height:880}});await ctx.addCookies([{name:cn,value:cv,url:O,httpOnly:true,sameSite:'Lax'}]);const page=await ctx.newPage(),creates:any[]=[];page.on('request',r=>{if(r.url().includes('/trpc/sessions.create'))creates.push({at:wall(),body:r.postData()})})
const out:any={at:wall(),issue:'POD-3112',kind:'r18-opencode-continuity',journeyId:'opencode-paired-final-tip',epicPin:epic,instance:P,ports:[port,hookPort,relayPort],providerPrompts:0}
let sid=''
const exact=(value:string)=>new RegExp(`^${value.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')}$`)
const workspaceDiagnostic=async(reason:string)=>{const labels=page.locator('[data-testid="project-group-label"]');const diagnostic={at:wall(),reason,refreshRepos:await m('discovery.refreshRepos',{}).catch((error:any)=>({error:String(error)})),machines:await q('machines.list').catch((error:any)=>({error:String(error)})),renderedProjectGroups:await labels.evaluateAll(nodes=>nodes.map(node=>{const el=node as HTMLElement,style=getComputedStyle(el),rect=el.getBoundingClientRect();return {text:el.innerText,ariaExpanded:el.getAttribute('aria-expanded'),hidden:el.hidden,display:style.display,visibility:style.visibility,opacity:style.opacity,rect:{width:rect.width,height:rect.height}}})).catch((error:any)=>[{error:String(error)}]),client:await page.evaluate(()=>{const root=globalThis as any,api=root.__podium;return {replicaPath:root.__podiumReplicaPath??null,terminalState:api?.state?.()??null,terminalDiagnostics:api?.diagnostics?.()??null,mountDiagnostics:root.__podiumTerminalDiagnostics?.snapshot?.()??[],switchTraces:root.__podiumSwitchTraces?.recent?.()??[],loading:Array.from(document.querySelectorAll('.app-loading')).map((node:any)=>({text:node.innerText,hidden:node.hidden,display:getComputedStyle(node).display}))}}).catch((error:any)=>({error:String(error)}))};(out.workspaceRefusals??=[]).push(diagnostic);return diagnostic}
const openWorkspace=async()=>{try{const projectName=page.locator('[data-testid="project-group-label"] > span:not([data-testid="project-group-count"])').filter({hasText:exact(workspace)}),groups=page.locator('[data-testid="project-group"]').filter({has:projectName});await groups.first().waitFor({state:'visible',timeout:30000});const count=await groups.count();if(count!==1)throw Error(`REFUSED registered project count ${count}`);const group=groups.first(),label=group.locator('[data-testid="project-group-label"]');if(await label.getAttribute('aria-expanded')!=='true')await label.click();const worktrees=group.locator('[data-testid="unified-worktree-row"]').getByTitle(C,{exact:true});const worktreeCount=await worktrees.count();if(worktreeCount===1){await worktrees.click();return 'worktree'}if(worktreeCount>1)throw Error(`REFUSED registered worktree count ${worktreeCount}`);const starts=group.locator('[data-testid="start-first-task"]');if(await starts.count()!==1)throw Error(`REFUSED registered project readiness ${await starts.count()}`);await starts.click();const deck=page.locator('[data-testid="cold-start-deck"]');await deck.waitFor({state:'visible',timeout:30000});const selected=deck.getByRole('button',{name:exact(`Project: ${workspace}`)});if(await selected.count()!==1)throw Error(`REFUSED selected project control ${await selected.count()}`);return 'cold'}catch(error){await workspaceDiagnostic(String(error));throw error}}
const compactWhitespace=(value:string)=>value.replace(/\s+/g,'')
const redactedNativeTail=(value:string)=>value.slice(-512).replace(/(?:sk-|bearer)[A-Za-z0-9._~+/=-]{8,}/gi,'[REDACTED_TOKEN]').replace(/[a-f0-9]{32,}/gi,'[REDACTED_HEX]').replace(/\/(?:home|Users)\/[^/]+/g,'/[REDACTED_HOME]')
const occurrences=(value:string,marker:string)=>marker.length===0?0:value.split(marker).length-1
const usableViews=async(marker:string)=>{const n=page.locator('[data-testid="mode-native"]'),c=page.locator('[data-testid="mode-chat"]');await n.waitFor({state:'visible',timeout:30000});await n.click();const opened=mono(),na=await n.getAttribute('aria-selected'),normalizedMarker=compactWhitespace(marker),nativeSamples=[] as any[];let normalizedTerminal='';for(let i=0;i<21;i++){const sample=await page.evaluate(()=>{const root=globalThis as any,api=root.__podium,text=api?.screenText?.()||'';return {at:new Date().toISOString(),text,state:api?.state?.()??null,diagnostics:api?.diagnostics?.()??null}}),normalized=compactWhitespace(sample.text),markerOccurrences=occurrences(normalized,normalizedMarker);normalizedTerminal=normalized;nativeSamples.push({at:sample.at,ms:mono()-opened,length:normalized.length,markerOccurrences,redactedNormalizedTail:redactedNativeTail(normalized),state:sample.state,diagnostics:sample.diagnostics});if(markerOccurrences>0)break;await sleep(250)}const terminalNormalizedMarkerOccurrences=occurrences(normalizedTerminal,normalizedMarker);await c.click();const ca=await c.getAttribute('aria-selected'),chat=await page.locator('[data-testid="chat-surface"]').innerText();return {native:na==='true'&&terminalNormalizedMarkerOccurrences>0,chat:ca==='true'&&chat.includes(marker),terminalNormalizedMarkerOccurrences,terminalNormalizedLength:normalizedTerminal.length,nativeSamples,chatMarkerOccurrences:occurrences(chat,marker),chatLength:chat.length}}
const enableRuntimeDrivers=async()=>{await page.getByRole('button',{name:'Settings',exact:true}).click();const settings=page.getByRole('dialog',{name:'Settings',exact:true});await settings.waitFor({state:'visible',timeout:30000});await settings.getByRole('button',{name:'Experimental',exact:true}).click();const label=settings.getByText('Headless session drivers',{exact:true});await label.waitFor({state:'visible',timeout:30000});const row=label.locator('..').locator('..'),toggle=row.getByRole('switch');if(await toggle.count()!==1)throw Error(`REFUSED runtime-drivers toggle count ${await toggle.count()}`);if(await toggle.getAttribute('aria-checked')!=='true'){await toggle.click();const save=settings.getByRole('button',{name:'Save changes',exact:true});await save.waitFor({state:'visible',timeout:10000});await save.click();await settings.getByText('Saved ✓',{exact:true}).waitFor({state:'visible',timeout:30000})}if(await toggle.getAttribute('aria-checked')!=='true')throw Error('REFUSED runtime-drivers setting not enabled');await settings.getByRole('button',{name:'Close settings',exact:true}).click();await settings.waitFor({state:'hidden',timeout:30000})}
try{
 const before=new Set((await list()).map((x:any)=>x.sessionId));await page.goto(O+'/?e2e=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!document.querySelector('.app-loading'),undefined,{timeout:90000});const d=page.getByRole('button',{name:/^Dismiss$/i}).first();if(await d.isVisible().catch(()=>false))await d.click();await enableRuntimeDrivers();if(await openWorkspace()!=='cold')throw Error('REFUSED fresh registered project was not empty');const collapse=page.locator('[data-testid="cold-start-collapse"]');if(await collapse.isVisible().catch(()=>false))await collapse.click();const agent=page.locator('[data-testid="cold-start-field"]').getByRole('button',{name:'Agent',exact:true});await agent.click();await page.getByRole('menuitem',{name:exact('OpenCode')}).click();if(!exact('OpenCode').test((await agent.innerText()).trim()))throw Error('REFUSED OpenCode not selected');const driver=page.locator('[data-testid="cold-start-field"]').getByRole('button',{name:'Driver',exact:true});if(await driver.count()!==1||!await driver.isVisible())throw Error(`REFUSED visible Driver control ${await driver.count()}`);await driver.click();await page.getByRole('menuitem',{name:exact('opencode-server')}).click();if(!exact('opencode-server').test((await driver.innerText()).trim()))throw Error(`REFUSED opencode-server not selected: ${await driver.innerText()}`);const launch=page.locator('[data-testid="cold-start-launch"]');if(await launch.getAttribute('aria-label')!=='Start a OpenCode session')throw Error(`REFUSED OpenCode launch readiness ${await launch.getAttribute('aria-label')}`);await launch.click()
 let row:any;for(let i=0;i<160;i++){row=(await list()).find((x:any)=>!before.has(x.sessionId)&&x.cwd===C);if(row?.driverId)break;await sleep(250)};if(row?.driverId!=='opencode-server'||row?.driverFamily!=='server'||!String(row?.accountId||'').startsWith('native:opencode'))throw Error('REFUSED identity '+JSON.stringify(row));sid=row.sessionId;const native=page.locator('[data-testid="mode-native"]');await native.waitFor({state:'visible',timeout:30000});if(await native.getAttribute('aria-selected')!=='true')throw Error('REFUSED not Native-first');await page.waitForFunction(()=>!!(window as any).__podium,undefined,{timeout:60000});let screen='';for(let i=0;i<240;i++){screen=await page.evaluate(()=>(window as any).__podium?.screenText()||'');if(screen.length>100&&/opencode/i.test(screen)&&!/not logged in|sign in required/i.test(screen))break;await sleep(250)};if(screen.length<100)throw Error('REFUSED CLI unavailable')
 out.launch={createRequests:creates,identity:rowIdentity(row),nativeFirst:true,screenLength:screen.length,rawRead:await read(sid)}
 const code='R18-'+Date.now().toString(36).toUpperCase(),nonce='P3112-R18-SEED-'+Date.now().toString(36).toUpperCase(),prompt=`Remember the codeword ${code}. Reply with exactly ${nonce}. Do not use tools.`;const t=mono(),w=wall(),beforeScreen=screen;const ta=page.locator('.xterm-helper-textarea:visible').last();await ta.focus();await page.keyboard.type(prompt,{delay:1});await page.keyboard.press('Enter');out.providerPrompts++;let working=null as number|null,growth=null as number|null;for(let i=0;i<480;i++){const [st,scr]=await Promise.all([stat(sid),page.evaluate(()=>(window as any).__podium?.screenText()||'')]),ms=mono()-t;if(working===null&&st?.phase==='working')working=ms;if(growth===null&&scr!==beforeScreen)growth=ms;if(working!==null&&growth!==null)break;await sleep(250)};const reply=await waitReply(sid,nonce);const seeded=(reply.read.items||[]),uc=seeded.filter((x:any)=>x.role==='user'&&String(x.text||'').includes(nonce)).length,ac=seeded.filter((x:any)=>x.role==='assistant'&&String(x.text||'').includes(nonce)).length;await page.locator('[data-testid="mode-chat"]').click();const chat=await page.locator('[data-testid="chat-surface"]').innerText();out.seed={at:w,codeword:code,nonce,workingMs:working,growthMs:growth,replyMs:reply.ms,userCount:uc,assistantCount:ac,chatOccurrences:chat.split(nonce).length-1,rawRead:reply.read};if(working===null||growth===null||reply.ms===null||uc!==1||ac!==1)throw Error('seed control failed')
 const journal0=journalSafe(sid);if(!journal0)throw Error('REFUSED missing opencode journal before A7a');const provider0=processProof(journal0.process.pid);if(journal0.workdir!==C||!provider0.exact)throw Error('REFUSED initial provider identity');out.beforeRestart={at:wall(),identity:rowIdentity((await list()).find((x:any)=>x.sessionId===sid)),status:await stat(sid),journal:journal0,provider:provider0,views:await usableViews(nonce),rawRead:await read(sid),daemonPid:Number(readFileSync(base+'/daemon.pid','utf8'))};writeFileSync(base+'/restart-ready',JSON.stringify({sid,at:wall()})+'\n');while(!await Bun.file(base+'/restart-done').exists())await sleep(250);const restart=JSON.parse(readFileSync(base+'/restart-done','utf8'))
 const adopted=await waitRow(sid,x=>x.status==='live',90000),afterRow=adopted.row,journalA=journalSafe(sid);if(!journalA)throw Error('REFUSED journal absent after daemon restart');const providerA=processProof(journalA.process.pid);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!document.querySelector('.app-loading'),undefined,{timeout:90000});await openWorkspace();const viewsA=await usableViews(nonce);out.a7a={restart,adoptMs:adopted.ms,before:out.beforeRestart.identity,after:rowIdentity(afterRow),journal:journalA,provider:providerA,sameProviderSession:journalA.opencodeSessionId===journal0.opencodeSessionId,sameProcessKey:journalA.process.key===journal0.process.key,sameSession:afterRow?.sessionId===sid,sameCreatedAt:afterRow?.createdAt===row.createdAt,sameResume:JSON.stringify(afterRow?.resume??null)===JSON.stringify(row?.resume??null),views:viewsA,rawRead:await read(sid)}
 await native.click();const r1='P3112-R18-A7A-'+Date.now().toString(36).toUpperCase(),p1=`What codeword did I ask you to remember? Reply with exactly ${code} ${r1}.`;await ta.focus();await page.keyboard.type(p1,{delay:1});await page.keyboard.press('Enter');out.providerPrompts++;const rr1=await waitReply(sid,r1);out.a7a.recall={nonce:r1,ms:rr1.ms,remembered:(rr1.read.items||[]).some((x:any)=>x.role==='assistant'&&String(x.text||'').includes(code)),rawRead:rr1.read};out.a7a.verdict=restart.oldPid!==restart.newPid&&out.a7a.sameProviderSession&&out.a7a.sameProcessKey&&providerA.exact&&out.a7a.sameSession&&out.a7a.sameCreatedAt&&out.a7a.sameResume&&viewsA.native&&viewsA.chat&&out.a7a.recall.remembered?'PASS':'FAIL';writeFileSync(base+'/a7a.json',JSON.stringify(out,null,2)+'\n');if(out.a7a.verdict!=='PASS')throw Error('A7a control failed');writeFileSync(base+'/a7a-ready',JSON.stringify({sid,at:wall(),evidence:'a7a.json'})+'\n');while(!existsSync(base+'/a7a-continue'))await sleep(250)
 const idle=await waitRow(sid,x=>x.phase==='idle',60000);const preH=(await list()).find((x:any)=>x.sessionId===sid),preParkJournal=journalSafe(sid);if(!preParkJournal)throw Error('REFUSED journal absent before hibernate');const preParkProvider=processProof(preParkJournal.process.pid);if(!preParkProvider.exact)throw Error('REFUSED provider not live before hibernate');const hAt=wall(),h=await m('sessions.hibernate',{sessionId:sid}),park=await waitRow(sid,x=>x.status==='hibernated',90000),parkRow=park.row,parkJournal=journalSafe(sid),parkProvider=processProof(preParkJournal.process.pid);if(parkProvider.live)throw Error('REFUSED provider survived hibernate');if(!parkJournal)throw Error('REFUSED journal absent after hibernate');if(parkJournal.opencodeSessionId!==journal0.opencodeSessionId||parkJournal.process.key!==journal0.process.key||parkJournal.process.pid!==preParkJournal.process.pid)throw Error('REFUSED unexpected parked journal identity');const rezAt=wall(),rz=await m('sessions.resurrect',{sessionId:sid}),live=await waitRow(sid,x=>x.status==='live',120000),liveRow=live.row,journalB=journalSafe(sid);if(!journalB)throw Error('REFUSED journal absent after resurrection');const providerB=processProof(journalB.process.pid);if(journalB.opencodeSessionId!==journal0.opencodeSessionId||journalB.process.key!==journal0.process.key||journalB.process.pid===preParkJournal.process.pid||!providerB.exact)throw Error('REFUSED resurrection provider identity')
 await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!document.querySelector('.app-loading'),undefined,{timeout:90000});await openWorkspace();const viewsB=await usableViews(r1);const r2='P3112-R18-A7B-'+Date.now().toString(36).toUpperCase(),p2=`Recall the original codeword. Reply with exactly ${code} ${r2}.`;await native.click();await ta.focus();await page.keyboard.type(p2,{delay:1});await page.keyboard.press('Enter');out.providerPrompts++;const rr2=await waitReply(sid,r2);const finalRow=(await list()).find((x:any)=>x.sessionId===sid);out.a7b={idle,hibernateAt:hAt,hibernate:h,parkMs:park.ms,parkIdentity:rowIdentity(parkRow),preParkJournal,preParkProvider,parkJournal,parkProvider,resurrectAt:rezAt,resurrect:rz,liveMs:live.ms,journal:journalB,provider:providerB,preIdentity:rowIdentity(preH),postIdentity:rowIdentity(liveRow),finalIdentity:rowIdentity(finalRow),sameProviderSession:journalB.opencodeSessionId===journal0.opencodeSessionId,sameProcessKey:journalB.process.key===journal0.process.key,newPid:journalB.process.pid!==preParkJournal.process.pid,sameSession:finalRow?.sessionId===sid,sameCreatedAt:finalRow?.createdAt===row.createdAt,sameResume:JSON.stringify(finalRow?.resume??null)===JSON.stringify(row?.resume??null),views:viewsB,recall:{nonce:r2,ms:rr2.ms,remembered:(rr2.read.items||[]).some((x:any)=>x.role==='assistant'&&String(x.text||'').includes(code)),rawRead:rr2.read},rawRead:await read(sid)};out.a7b.verdict=parkRow?.status==='hibernated'&&!parkProvider.live&&out.a7b.sameProviderSession&&out.a7b.sameProcessKey&&out.a7b.newPid&&providerB.exact&&out.a7b.sameSession&&out.a7b.sameCreatedAt&&out.a7b.sameResume&&viewsB.native&&viewsB.chat&&out.a7b.recall.remembered?'PASS':'FAIL';out.verdict=out.a7b.verdict
 await page.screenshot({path:base+'/continuity.png',fullPage:true})
}catch(e){out.verdict='REFUSED';out.reason=String(e)}finally{out.finishedAt=wall();writeFileSync(base+'/r18-reading.json',JSON.stringify(out,null,2)+'\n');await browser.close().catch(()=>{})};console.log(JSON.stringify({verdict:out.verdict,sid,a7a:out.a7a?.verdict,a7b:out.a7b?.verdict,reason:out.reason},null,2))
