-- A2 · THE SECOND OWNER COLUMN GOES (spec: multi-user epic A2, ADR 9 Amendment 1 D10)
--
-- `20260912164233_a2-ownership-backfill` has already read every `assignee`,
-- adjudicated the ambiguous ones and written its findings to
-- `ownership_migration_dispositions`. What is left in this column is either equal
-- to `owner_user_id` or recorded as retired. The value is gone from the model,
-- from the stores and from the service; this is the last copy.
--
-- WHY DROP IT RATHER THAN LEAVE IT UNWRITTEN. A column nothing writes today is a
-- column something writes next quarter — and the specific failure this epic is
-- correcting is not that the two columns held wrong values, it is that the schema
-- MADE TWO ANSWERS REPRESENTABLE. Leaving the column and relying on discipline
-- reproduces the original bug with a shorter half-life. With it dropped, "owner
-- and assignee disagree" is not a state this database can hold, and the wire key
-- `assignee` is a projection of `owner_user_id` with no storage of its own.
--
-- SEPARATE MIGRATION, and the split is the point: the backfill had to be able to
-- READ this column to adjudicate it. A single migration doing both would leave no
-- state in which the evidence and the source value both existed, so a failure
-- between the two halves would lose the thing the evidence is about.
--
-- ONE CONSEQUENCE, RECORDED WHERE THE NEXT READER WILL BE.
--
-- `20260911082826_retire-the-solo-user` is frozen history and its SQL includes
-- `UPDATE issues SET assignee = ... WHERE assignee = 'user:sole'`. After this
-- migration that statement names a column that does not exist, so REPLAYING that
-- file against a post-A2 schema fails.
--
-- The normal path never replays: `runDrizzleMigrations` applies only the pending
-- set, filtered by ledger name. The one path that would is the ALIAS case the
-- runner's own comment names — an instance whose ledger holds an OLD NAME for a
-- migration, which makes the canonical name read as pending. Such a replay now
-- errors loudly, inside drizzle's transaction and after the boot backup, rather
-- than corrupting anything; but anyone introducing a migration alias that covers
-- the solo-user retirement needs to know it can no longer be replayed. Reported to
-- the phase review (PDM-131) rather than left for someone to rediscover.

-- `ALTER TABLE ... DROP COLUMN` rather than the create/copy/drop/rename rebuild
-- `20260911082826_retire-the-solo-user` used: that one was removing column
-- DEFAULTS, which SQLite cannot do in place. Dropping a column it can, and a
-- rebuild would needlessly rewrite the whole table and every index on it.

ALTER TABLE `issues` DROP COLUMN `assignee`;
