/**
 * Regenerates src/features/setup/podium-ascii.ts from podium-ascii-src.svg.
 *
 * The login screen's ASCII wordmark is precomputed (spec: Podium Login 2b Handoff):
 * the SVG is alpha-sampled on a 96×22 grid (4× supersampled), coverage < 0.45 is
 * dropped, and the rest is quantized to 4 bits per cell. The runtime maps coverage
 * to a density ramp — statically, or per-frame for the idle shimmer.
 *
 * Needs a browser for rasterization:  bun run scripts/generate-login-ascii.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from '@playwright/test'

const here = dirname(fileURLToPath(import.meta.url))
const svg = readFileSync(join(here, 'podium-ascii-src.svg'), 'utf8')

const COLS = 96
const VIEW_W = 826.4
const VIEW_H = 317.7
const ROWS = Math.round(COLS * (VIEW_H / VIEW_W) * 0.6)
const SS = 4
const THRESHOLD = 0.45

const browser = await chromium.launch()
const page = await browser.newPage()
const grid = await page.evaluate(
  async ({ svg, cols, rows, ss, threshold }) => {
    const img = new Image()
    const loaded = new Promise<void>((resolve, reject) => {
      img.onload = () => resolve()
      img.onerror = () => reject(new Error('svg failed to load'))
    })
    img.src = `data:image/svg+xml;base64,${btoa(svg)}`
    await loaded
    const c = document.createElement('canvas')
    c.width = cols * ss
    c.height = rows * ss
    const ctx = c.getContext('2d')
    if (!ctx) throw new Error('no 2d context')
    ctx.drawImage(img, 0, 0, cols * ss, rows * ss)
    const data = ctx.getImageData(0, 0, cols * ss, rows * ss).data
    const lines: string[] = []
    for (let y = 0; y < rows; y++) {
      let line = ''
      for (let x = 0; x < cols; x++) {
        let sum = 0
        for (let sy = 0; sy < ss; sy++)
          for (let sx = 0; sx < ss; sx++)
            sum += data[((y * ss + sy) * cols * ss + x * ss + sx) * 4 + 3]
        const a = sum / (ss * ss * 255)
        line += a < threshold ? '0' : Math.round(a * 15).toString(16)
      }
      lines.push(line)
    }
    return lines
  },
  { svg, cols: COLS, rows: ROWS, ss: SS, threshold: THRESHOLD },
)
await browser.close()

const out = `// Generated by scripts/generate-login-ascii.ts — do not edit by hand.
// PODIUM wordmark alpha-sampled to a ${COLS}×${ROWS} coverage grid; one hex nibble
// per cell (0 = below the ${THRESHOLD} coverage threshold, i.e. blank).

export const ASCII_COLS = ${COLS}
export const ASCII_ROWS = ${ROWS}

export const ASCII_COVERAGE: readonly string[] = [
${grid.map((l) => `  '${l}',`).join('\n')}
]
`
writeFileSync(join(here, '..', 'src', 'features', 'setup', 'podium-ascii.ts'), out)
console.log(`wrote ${COLS}×${ROWS} grid`)
