/**
 * Generate the three animated raster alpha masks used by WorkingMark.
 *
 * The old mark animated every SVG circle. Chromium laid out the page on most
 * animation frames, so two visible marks consumed a large fraction of one
 * renderer core. These strips sample the same per-dot opacity, scale, delays,
 * and 1.5 s cycle at 30 fps. Each APNG frame occupies only one 66×100 cell:
 * WebKit no longer updates an external SVG mask or traverses the compositing
 * tree for a translated, 4500%-height layer. Keep the SVG strips as geometry
 * sources. PNG's animation chunks are defined in https://www.w3.org/TR/png-3/.
 *
 * Usage: bun apps/web/scripts/generate-working-mark-sprites.ts
 */
import sharp from 'sharp'
import { deflateSync } from 'node:zlib'

const FRAME_COUNT = 45
const CYCLE_MS = 1_500
const DOTS: ReadonlyArray<readonly [number, number, number]> = [
  [17, 18, 0],
  [49, 18, 120],
  [17, 39, 210],
  [49, 39, 330],
  [17, 61, 420],
  [49, 61, 540],
  [17, 82, 630],
  [49, 82, 750],
]

const RADII = {
  small: 11,
  medium: 10.5,
  large: 9.5,
} as const

function pngChunk(type: string, data: Buffer): Buffer {
  const name = Buffer.from(type)
  let crc = 0xffffffff
  for (const byte of Buffer.concat([name, data])) {
    crc ^= byte
    for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0)
  }
  const length = Buffer.alloc(4)
  length.writeUInt32BE(data.length)
  const checksum = Buffer.alloc(4)
  checksum.writeUInt32BE((crc ^ 0xffffffff) >>> 0)
  return Buffer.concat([length, name, data, checksum])
}

/** Full-cell, source-blended frames prevent alpha from accumulating on loops. */
function animatedMask(pixels: Buffer, width: number): Buffer {
  const header = Buffer.alloc(13)
  header.writeUInt32BE(width, 0)
  header.writeUInt32BE(100, 4)
  header[8] = 8 // RGBA, eight bits per channel.
  header[9] = 6
  const animation = Buffer.alloc(8)
  animation.writeUInt32BE(FRAME_COUNT, 0) // Zero plays means loop forever.
  const chunks = [
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    pngChunk('IHDR', header),
    pngChunk('acTL', animation),
  ]
  let sequence = 0
  for (let frame = 0; frame < FRAME_COUNT; frame++) {
    const control = Buffer.alloc(26)
    control.writeUInt32BE(sequence++, 0)
    control.writeUInt32BE(width, 4)
    control.writeUInt32BE(100, 8)
    control.writeUInt16BE(CYCLE_MS, 20)
    control.writeUInt16BE(FRAME_COUNT * 1000, 22)
    chunks.push(pngChunk('fcTL', control))
    const stride = width * 4
    const scanlines = Buffer.alloc((stride + 1) * 100)
    for (let y = 0; y < 100; y++) {
      const start = (frame * 100 + y) * stride
      pixels.copy(scanlines, y * (stride + 1) + 1, start, start + stride)
    }
    const compressed = deflateSync(scanlines)
    if (frame === 0) chunks.push(pngChunk('IDAT', compressed))
    else {
      const frameSequence = Buffer.alloc(4)
      frameSequence.writeUInt32BE(sequence++)
      chunks.push(pngChunk('fdAT', Buffer.concat([frameSequence, compressed])))
    }
  }
  chunks.push(pngChunk('IEND', Buffer.alloc(0)))
  return Buffer.concat(chunks)
}

function lerp(from: number, to: number, amount: number): number {
  return from + (to - from) * amount
}

function dotFrame(elapsedMs: number, delayMs: number): { opacity: number; scale: number } {
  const shifted = ((elapsedMs - delayMs) % CYCLE_MS + CYCLE_MS) % CYCLE_MS
  const progress = shifted / CYCLE_MS
  if (progress <= 0.16) {
    const amount = progress / 0.16
    return { opacity: lerp(0.2, 1, amount), scale: lerp(0.8, 1.16, amount) }
  }
  if (progress <= 0.44) {
    const amount = (progress - 0.16) / (0.44 - 0.16)
    return { opacity: lerp(1, 0.2, amount), scale: lerp(1.16, 0.8, amount) }
  }
  return { opacity: 0.2, scale: 0.8 }
}

function fixed(value: number): string {
  return value.toFixed(3).replace(/\.?0+$/, '')
}

function sprite(radius: number, label: string): string {
  const circles: string[] = []
  for (let frame = 0; frame < FRAME_COUNT; frame++) {
    const elapsedMs = (frame / FRAME_COUNT) * CYCLE_MS
    for (const [cx, cy, delay] of DOTS) {
      const state = dotFrame(elapsedMs, delay)
      // A static 20%-opaque, 0.8-scale cell sits under this mask. Source-over
      // needs this adjusted alpha to reproduce the original final opacity.
      const overlayOpacity = Math.max(0, (state.opacity - 0.2) / 0.8)
      if (overlayOpacity <= 0.0005) continue
      circles.push(
        `  <circle cx="${cx}" cy="${fixed(cy + frame * 100)}" r="${fixed(radius * state.scale)}" fill="#fff" fill-opacity="${fixed(overlayOpacity)}"/>`,
      )
    }
  }
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- Generated by apps/web/scripts/generate-working-mark-sprites.ts (${label}). -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 66 ${FRAME_COUNT * 100}" shape-rendering="geometricPrecision">`,
    ...circles,
    '</svg>',
    '',
  ].join('\n')
}

await Promise.all(
  Object.entries(RADII).map(([label, radius]) =>
    (async () => {
      const source = sprite(radius, label)
      await Bun.write(new URL(`../src/lib/motion/working-mark-${label}.svg`, import.meta.url), source)
      const { data, info } = await sharp(Buffer.from(source))
        .ensureAlpha()
        .raw()
        .toBuffer({ resolveWithObject: true })
      await Bun.write(
        new URL(`../src/lib/motion/working-mark-${label}.png`, import.meta.url),
        animatedMask(data, info.width),
      )
    })(),
  ),
)
