/**
 * Generate the three alpha-mask frame strips used by WorkingMark.
 *
 * The old mark animated every SVG circle. Chromium laid out the page on most
 * animation frames, so two visible marks consumed a large fraction of one
 * renderer core. These strips sample the same per-dot opacity, scale, delays,
 * and 1.5 s cycle at 30 fps while CSS moves one layer on the compositor.
 *
 * Usage: bun apps/web/scripts/generate-working-mark-sprites.ts
 */

const FRAME_COUNT = 45
const CYCLE_MS = 1_500
const DOTS: ReadonlyArray<readonly [number, number, number]> = [
  [17, 18, 0],
  [49, 18, 120],
  [17, 39, 210],
  [49, 39, 330],
  [17, 61, 420],
  [49, 61, 540],
  [17, 82, 630],
  [49, 82, 750],
]

const RADII = {
  small: 11,
  medium: 10.5,
  large: 9.5,
} as const

function lerp(from: number, to: number, amount: number): number {
  return from + (to - from) * amount
}

function dotFrame(elapsedMs: number, delayMs: number): { opacity: number; scale: number } {
  const shifted = ((elapsedMs - delayMs) % CYCLE_MS + CYCLE_MS) % CYCLE_MS
  const progress = shifted / CYCLE_MS
  if (progress <= 0.16) {
    const amount = progress / 0.16
    return { opacity: lerp(0.2, 1, amount), scale: lerp(0.8, 1.16, amount) }
  }
  if (progress <= 0.44) {
    const amount = (progress - 0.16) / (0.44 - 0.16)
    return { opacity: lerp(1, 0.2, amount), scale: lerp(1.16, 0.8, amount) }
  }
  return { opacity: 0.2, scale: 0.8 }
}

function fixed(value: number): string {
  return value.toFixed(3).replace(/\.?0+$/, '')
}

function sprite(radius: number, label: string): string {
  const circles: string[] = []
  for (let frame = 0; frame < FRAME_COUNT; frame++) {
    const elapsedMs = (frame / FRAME_COUNT) * CYCLE_MS
    for (const [cx, cy, delay] of DOTS) {
      const state = dotFrame(elapsedMs, delay)
      // A static 20%-opaque, 0.8-scale cell sits under this mask. Source-over
      // needs this adjusted alpha to reproduce the original final opacity.
      const overlayOpacity = Math.max(0, (state.opacity - 0.2) / 0.8)
      if (overlayOpacity <= 0.0005) continue
      circles.push(
        `  <circle cx="${cx}" cy="${fixed(cy + frame * 100)}" r="${fixed(radius * state.scale)}" fill="#fff" fill-opacity="${fixed(overlayOpacity)}"/>`,
      )
    }
  }
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- Generated by apps/web/scripts/generate-working-mark-sprites.ts (${label}). -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 66 ${FRAME_COUNT * 100}" shape-rendering="geometricPrecision">`,
    ...circles,
    '</svg>',
    '',
  ].join('\n')
}

await Promise.all(
  Object.entries(RADII).map(([label, radius]) =>
    Bun.write(
      new URL(`../src/lib/motion/working-mark-${label}.svg`, import.meta.url),
      sprite(radius, label),
    ),
  ),
)
