// apps/desktop/src-tauri/tauri-conf.test.ts
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const conf = JSON.parse(readFileSync(join(__dirname, 'tauri.conf.json'), 'utf8'))
const defaultCapability = JSON.parse(
  readFileSync(join(__dirname, 'capabilities/default.json'), 'utf8'),
)
const mainSource = readFileSync(join(__dirname, 'src/main.rs'), 'utf8')
const nativeOpenSource = readFileSync(join(__dirname, 'native-open.js'), 'utf8')
const bootstrapSource = readFileSync(join(__dirname, 'src/bootstrap.rs'), 'utf8')
const repairPermission = readFileSync(
  join(__dirname, 'permissions/autogenerated/repair_payload.toml'),
  'utf8',
)
const cargoSource = readFileSync(join(__dirname, 'Cargo.toml'), 'utf8')
const webStyles = readFileSync(join(__dirname, '../../web/src/styles.css'), 'utf8')
const webMainSource = readFileSync(join(__dirname, '../../web/src/app/main.tsx'), 'utf8')
const webLinkHostSource = readFileSync(
  join(__dirname, '../../web/src/components/PodiumLinkHost.tsx'),
  'utf8',
)

describe('tauri desktop config', () => {
  it('registers podium as a static desktop deep-link scheme', () => {
    expect(conf.plugins['deep-link']).toEqual({ desktop: { schemes: ['podium'] } })
    expect(cargoSource).toContain('tauri-plugin-deep-link = "2"')
    expect(cargoSource).toContain('features = ["deep-link"]')
  })

  it('keeps single-instance first and delivers cold plus warm links through one queue', () => {
    const singleInstance = mainSource.indexOf('tauri_plugin_single_instance::init')
    const deepLink = mainSource.indexOf('tauri_plugin_deep_link::init')
    const updater = mainSource.indexOf('tauri_plugin_updater::Builder')
    expect(singleInstance).toBeGreaterThan(-1)
    expect(deepLink).toBeGreaterThan(singleInstance)
    expect(updater).toBeGreaterThan(deepLink)
    expect(mainSource).toContain('app.deep_link().get_current()?')
    expect(mainSource).toContain('app.deep_link().on_open_url')
    expect(mainSource).toContain('app.deep_link().register_all()')
    expect(nativeOpenSource).toContain("new CustomEvent('podium:native-open', { detail: raw })")
    expect(nativeOpenSource).toContain('window.__PODIUM_NATIVE_OPEN_READY__')
    expect(mainSource).toContain('const NATIVE_OPEN_QUEUE_CAPACITY: usize = 32')
    expect(nativeOpenSource).toContain('const PENDING_CAPACITY = 32')
    expect(webLinkHostSource).toContain('PODIUM_LINK_QUEUE_CAPACITY = 32')
    expect(mainSource).toContain('enqueue_native_open(queue, raw)')
    expect(mainSource).toContain('drain_native_open_queue(queue, |raw|')
    expect(mainSource).toContain('flush_native_open_queue(&window, &page_open_queue)')
    const warmDelivery = mainSource.slice(
      mainSource.indexOf('fn deliver_or_queue_native_open'),
      mainSource.indexOf('fn flush_native_open_queue'),
    )
    expect(warmDelivery.indexOf('enqueue_native_open(queue, raw)')).toBeGreaterThan(-1)
    expect(warmDelivery.indexOf('window.show()')).toBeGreaterThan(
      warmDelivery.indexOf('enqueue_native_open(queue, raw)'),
    )
    expect(warmDelivery.indexOf('window.set_focus()')).toBeGreaterThan(
      warmDelivery.indexOf('window.show()'),
    )
    expect(warmDelivery.indexOf('flush_native_open_queue(&window, queue)')).toBeGreaterThan(
      warmDelivery.indexOf('window.set_focus()'),
    )
    const listener = webLinkHostSource.indexOf(
      'window.addEventListener(PODIUM_NATIVE_OPEN_EVENT, onNativeOpen)',
    )
    const ready = webLinkHostSource.indexOf('__PODIUM_NATIVE_OPEN_READY__?.(true)')
    expect(listener).toBeGreaterThan(-1)
    expect(ready).toBeGreaterThan(listener)
    expect(webLinkHostSource).toContain('__PODIUM_NATIVE_OPEN_READY__?.(false)')
    expect(webLinkHostSource).toContain('pendingHrefs.current.push(pendingPodiumHref(detail))')
  })

  it('defines a bundled-page CSP and keeps ambient capabilities empty of plugin defaults', () => {
    const csp = conf.app.security.csp as string
    expect(csp).toContain("default-src 'self'")
    expect(csp).toContain("script-src 'self'")
    expect(csp).toContain("object-src 'none'")
    expect(csp).toContain("frame-ancestors 'none'")
    expect(csp).not.toContain("'unsafe-eval'")
    expect(defaultCapability.permissions).toEqual([
      'core:event:allow-listen',
      'core:event:allow-unlisten',
    ])
    expect(JSON.stringify(defaultCapability.permissions)).not.toContain(':default')
    expect(mainSource.match(/\.permission\("opener:allow-default-urls"\)/g)).toHaveLength(2)
  })

  it('keeps stable as the packaged fallback endpoint', () => {
    expect(conf.plugins.updater.endpoints).toEqual([
      'https://github.com/madeinorbit/podium/releases/latest/download/latest.json',
    ])
  })
  it('bundles native icon formats for every desktop platform', () => {
    expect(conf.bundle.icon).toEqual([
      'icons/32x32.png',
      'icons/128x128.png',
      'icons/128x128@2x.png',
      'icons/icon.icns',
      'icons/icon.ico',
    ])
    for (const icon of conf.bundle.icon) {
      expect(existsSync(join(__dirname, icon)), icon).toBe(true)
    }
  })
  it('bundles one complete headless payload as the first-run seed', () => {
    expect(conf.bundle.resources).toEqual(['resources/payload'])
    expect(mainSource).toContain('"PODIUM_MOBILE_WEB_DIR"')
    expect(mainSource).toContain('.join("mobile")')
  })

  it('strips quarantine before publishing the one-time external seed', () => {
    expect(bootstrapSource).toContain('Command::new("/usr/bin/xattr")')
    expect(bootstrapSource).toContain('.args(["-dr", "com.apple.quarantine"])')
    const seed = bootstrapSource.slice(
      bootstrapSource.indexOf('pub fn seed_payload_if_absent'),
      bootstrapSource.indexOf('pub fn ensure_executable'),
    )
    expect(seed.indexOf('strip_payload_quarantine(&staging)')).toBeGreaterThan(-1)
    expect(seed.indexOf('std::fs::rename(&staging, install)')).toBeGreaterThan(
      seed.indexOf('strip_payload_quarantine(&staging)'),
    )
  })

  it('keeps repair reachable from the baked fallback when the payload cannot serve', () => {
    expect(mainSource).toContain('window.__PODIUM_PAYLOAD_UNAVAILABLE__ = true')
    expect(mainSource).toContain('repairPayload: () =>')
    expect(mainSource).toContain("invoke('repair_payload')")
    expect(repairPermission).toContain('identifier = "allow-repair-payload"')
    expect(repairPermission).toContain('commands.allow = ["repair_payload"]')
    expect(mainSource).toContain('.permission("allow-repair-payload")')
    expect(webMainSource).toContain('function PayloadUnavailablePage(')
    expect(webMainSource).toContain("label: repairing ? 'Repairing…' : 'Repair payload'")
    expect(webMainSource).toContain('nativeDesktopBridge()?.repairPayload')
  })

  it('routes a broken installed payload to signed repair and leaves healthy startup alone', () => {
    const payloadStartup = mainSource.slice(
      mainSource.indexOf('let mut payload_start_error'),
      mainSource.indexOf('// One canonical list backs both startup'),
    )
    const windowRouting = mainSource.slice(
      mainSource.indexOf('let payload_start_error_for_window'),
      mainSource.indexOf('// External-link shim (ALL modes)'),
    )

    // Present-but-unrunnable is not reseeded and must not abort setup: executable and spawn
    // failures become data consumed by the signed window-construction path.
    expect(payloadStartup).toContain('match bootstrap::ensure_executable')
    expect(payloadStartup).not.toContain(
      'bootstrap::ensure_executable(&install.join("podium")).map_err',
    )
    expect(payloadStartup).toContain('payload_start_error = Some(reason)')
    expect(payloadStartup).toContain('payload spawn failed: {error}')
    expect(payloadStartup).toContain('daemon payload spawn failed: {error}')

    // A broken startup selects the baked document and its native repair bridge first. With no
    // error, the same code continues through the existing healthy local and remote targets.
    expect(windowRouting.indexOf('if let Some(error) = payload_start_error_for_window')).toBeLessThan(
      windowRouting.indexOf('else if let Some(port) = wait_local_port'),
    )
    expect(windowRouting).toContain(
      '(WebviewUrl::default(), payload_unavailable_injection(&error))',
    )
    expect(windowRouting).toContain('(bootstrap::local_window_target(port, ready), injection)')
    expect(windowRouting).toContain('(webview_url, remote_init_injection)')
    expect(mainSource).toContain('window.__PODIUM_PAYLOAD_ERROR__ = {error_literal}')
    expect(mainSource).toContain('app.restart();')
    expect(webMainSource).toContain('<PayloadUnavailablePage reason={payloadStartupError} />')
    expect(webMainSource).toContain("label: 'Startup failure'")
  })

  it('keeps crash supervision attached across parent self-handover', () => {
    expect(mainSource).toContain(
      'const DESKTOP_SUCCESSOR_FILE_ENV: &str = "PODIUM_DESKTOP_SUCCESSOR_FILE"',
    )
    expect(mainSource).toContain('take_live_successor_pid(path)')
    expect(mainSource).toContain('follow_successor_chain(path, pid, &successor, &shutting_down)')
    expect(mainSource).toContain('reap_tracked_successor(app)')
  })

  it('loads the all-in-one UI from the local server with a stable port (POD-2510)', () => {
    // Served-local: prefer the sidecar origin; baked frontendDist is fallback only.
    expect(mainSource).toContain('resolve_local_port')
    expect(mainSource).toContain('local_window_target')
    expect(mainSource).toContain('local_served_http_url')
    // frontendDist remains packaged as the offline / boot-race fallback.
    expect(conf.build.frontendDist).toBe('../../web/dist')
  })

  it('keeps the baked document at the URL the fallback navigates to (POD-2510)', () => {
    // bootstrap::baked_document_url() hard-codes `tauri://localhost` (and the Windows
    // `http://tauri.localhost` form). Two config keys would move that URL out from under it:
    // a devUrl replaces it in dev, and useHttpsScheme makes the Windows form https.
    expect(conf.build.devUrl).toBeUndefined()
    for (const window of conf.app?.windows ?? []) {
      expect(window.useHttpsScheme).toBeUndefined()
    }
  })
})

/**
 * The shell tells the page which launch mode it is in, and the update dialog renders one row
 * (all-in-one) or two (a device driving a remote server) off that answer. Since POD-2510 the
 * all-in-one page is SERVED — `http://127.0.0.1:<port>` — which is the same http shape a
 * transferred remote page has, so the shell emits the served origin it chose and the page
 * compares against it.
 *
 * The bug this replaces was a JS expression that read correctly and returned the wrong string,
 * so this lifts the real expression out of main.rs and EVALUATES it. A substring assertion
 * could not have failed on it.
 */
describe('served-local launchMode classification (POD-2510)', () => {
  const SERVED_ORIGIN = 'http://127.0.0.1:18787'
  const template = mainSource.match(/const LOCAL_LAUNCH_MODE_EXPRESSION: &str = "([^"]*)";/)?.[1]

  function classify(location: Record<string, string>, launchMode = 'all-in-one'): unknown {
    if (!template) throw new Error('LOCAL_LAUNCH_MODE_EXPRESSION not found in main.rs')
    const expression = template
      .replaceAll('{served_origin_literal}', JSON.stringify(SERVED_ORIGIN))
      .replaceAll('{launch_mode_literal}', JSON.stringify(launchMode))
    return new Function('window', `return ${expression}`)({ location })
  }

  it('finds the expression in the shell source', () => {
    expect(template).toBeTruthy()
  })

  it('calls the served-local page this shell served exactly what it launched as', () => {
    for (const mode of ['all-in-one', 'server']) {
      expect(
        classify({ protocol: 'http:', hostname: '127.0.0.1', origin: SERVED_ORIGIN }, mode),
      ).toBe(mode)
    }
  })

  it('calls the baked fallback document local too', () => {
    expect(
      classify({
        protocol: 'tauri:',
        hostname: 'localhost',
        origin: 'tauri://localhost',
      }),
    ).toBe('all-in-one')
    expect(
      classify({
        protocol: 'http:',
        hostname: 'tauri.localhost',
        origin: 'http://tauri.localhost',
      }),
    ).toBe('all-in-one')
  })

  it('calls a page transferred to a remote server daemon', () => {
    expect(
      classify({
        protocol: 'https:',
        hostname: 'podium.example',
        origin: 'https://podium.example',
      }),
    ).toBe('daemon')
    // A different loopback port is a different server — someone else's, not ours.
    expect(
      classify({
        protocol: 'http:',
        hostname: '127.0.0.1',
        origin: 'http://127.0.0.1:19999',
      }),
    ).toBe('daemon')
  })
  it('ships the entitlements notarization requires', () => {
    // Without an entitlements file the hardened runtime kills the JIT the bundled Bun sidecar
    // needs, and without the hardened runtime Apple refuses to notarize at all.
    expect(conf.bundle.macOS.entitlements).toBe('entitlements.plist')
    for (const plist of ['entitlements.plist', 'entitlements.sidecar.plist']) {
      const path = join(__dirname, plist)
      expect(existsSync(path), plist).toBe(true)
      expect(readFileSync(path, 'utf8')).toContain('com.apple.security.cs.allow-jit')
      // codesign parses entitlements with AMFIUnserializeXML, a restricted reader that rejects
      // XML comments outright ("syntax error near line N") even though they are valid XML. The
      // natural instinct — explaining these entitlements inline — breaks every macOS build, so
      // the rationale lives in docs/desktop-releases.md instead.
      expect(readFileSync(path, 'utf8'), `${plist} must not contain XML comments`).not.toContain(
        '<!--',
      )
    }
    // The sidecar is the one that allocates writable-executable memory; the shell must not.
    expect(readFileSync(join(__dirname, 'entitlements.sidecar.plist'), 'utf8')).toContain(
      'com.apple.security.cs.allow-unsigned-executable-memory',
    )
    expect(readFileSync(join(__dirname, 'entitlements.plist'), 'utf8')).not.toContain(
      'com.apple.security.cs.allow-unsigned-executable-memory',
    )
  })

  it('claims ⌘N in the macOS menu and routes it to the web app (POD-790)', () => {
    // An accelerator no menu item owns never reaches the webview, so this item
    // IS the shortcut — a JS keydown handler alone could not see ⌘N.
    expect(mainSource).toContain('MenuItemBuilder::with_id("new-agent", "New Agent")')
    expect(mainSource).toContain('.accelerator("CmdOrCtrl+N")')
    // The web app's half of the contract: apps/web/src/features/worklist/spawn-row.tsx.
    expect(mainSource).toContain('__PODIUM_NEW_AGENT__')
  })

  it('owns About, updates, Settings, Add Project, and View sidebar toggles', () => {
    expect(mainSource).toContain('MenuItemBuilder::with_id("about-podium", "About Podium ADE")')
    expect(mainSource).toContain('MenuItemBuilder::with_id("check-updates", "Check for Updates…")')
    expect(mainSource).toContain('MenuItemBuilder::with_id("open-settings", "Settings…")')
    // ⌘, is where macOS users look for preferences, and only a menu item can
    // claim it — an unowned accelerator never reaches WKWebView.
    expect(mainSource).toMatch(/"open-settings"[^;]*\.accelerator\("CmdOrCtrl\+,"\)/)
    expect(mainSource).toContain('MenuItemBuilder::with_id("add-project", "Add Project…")')
    expect(mainSource).toContain(
      'MenuItemBuilder::with_id("toggle-left-sidebar", "Toggle Left Sidebar")',
    )
    expect(mainSource).toContain(
      'MenuItemBuilder::with_id("toggle-flight-deck", "Toggle Flight Deck")',
    )
    expect(mainSource).toContain(
      'MenuItemBuilder::with_id("toggle-right-sidebar", "Toggle Right Sidebar")',
    )
    // Pin the pairing, not just the two chords: the bare ⌘B belongs to the
    // right dock and ⇧⌘B to the left work list. Asserting the id and the
    // accelerator separately stays green through a swap. `[^;]*` keeps each
    // match inside its own let-statement so it cannot borrow the other
    // item's accelerator.
    expect(mainSource).toMatch(/"toggle-right-sidebar"[^;]*\.accelerator\("CmdOrCtrl\+B"\)/)
    expect(mainSource).toMatch(/"toggle-left-sidebar"[^;]*\.accelerator\("Shift\+CmdOrCtrl\+B"\)/)
    expect(mainSource).toContain('__PODIUM_ABOUT__')
    expect(mainSource).toContain('__PODIUM_CHECK_UPDATES__')
    expect(mainSource).toContain('__PODIUM_SETTINGS__')
    expect(mainSource).toContain('__PODIUM_ADD_PROJECT__')
    expect(mainSource).toContain('__PODIUM_TOGGLE_LEFT_SIDEBAR__')
    expect(mainSource).toContain('__PODIUM_TOGGLE_FLIGHT_DECK__')
    expect(mainSource).toContain('__PODIUM_TOGGLE_RIGHT_SIDEBAR__')
  })

  it('names Hide and Quit after the product, not the running binary', () => {
    // The predefined items default to NSRunningApplication.localizedName, which
    // under `tauri dev` is the bare cargo executable — "Quit Podium", the bin
    // target name. The bundle reads the display name below; explicit text is
    // what keeps dev showing the shipped menu.
    expect(mainSource).toContain('.hide_with_text("Hide Podium ADE")')
    expect(mainSource).toContain('.quit_with_text("Quit Podium ADE")')
    expect(mainSource).not.toContain('.quit()')
  })

  /**
   * The app is called "Podium ADE" everywhere a person reads it, WITHOUT
   * renaming the product. `productName` is not just a label: it names the .app,
   * the DMG, the AppImage and the `.app.tar.gz` the updater manifest points at,
   * and GitHub rewrites spaces in release asset names to dots — so a
   * "Podium ADE" productName would publish `Podium.ADE.app.tar.gz` under a
   * manifest URL claiming `Podium ADE.app.tar.gz` and break auto-update.
   *
   * macOS separates the two on purpose. CFBundleName (Tauri's `bundleName`)
   * titles the menu bar, the Dock tile, ⌘-Tab and Force Quit; CFBundleDisplayName
   * titles the item in Finder. Neither touches a filename.
   */
  it('shows the product name without renaming the bundle (POD-1199)', () => {
    expect(conf.productName).toBe('Podium')
    expect(conf.bundle.macOS.bundleName).toBe('Podium ADE')
    expect(conf.bundle.macOS.infoPlist).toBe('Info.plist')
    const plist = readFileSync(join(__dirname, conf.bundle.macOS.infoPlist), 'utf8')
    expect(plist).toContain('<key>CFBundleDisplayName</key>')
    expect(plist).toContain('<string>Podium ADE</string>')
    // The window title is the one name that is not macOS-only.
    expect(mainSource).toContain('.title("Podium ADE")')
  })

  it('names the executable after the product, for the Dock (POD-1119)', () => {
    // The menu bar can be titled from Rust (above); the Dock tile cannot. For an
    // unbundled process macOS reads ProcessInfo.processName — argv[0]'s basename
    // — so under `tauri dev` the app name IS this bin target's name, and a
    // `podium-desktop` here surfaces as a "podium-desktop" tile. Packaged builds
    // read the display name and are unaffected either way. It stays the bare
    // product word because cargo derives the crate name from the target name,
    // so the target cannot carry the space in "Podium ADE".
    expect(cargoSource).toMatch(/\[\[bin\]\][\s\S]*?\nname = "Podium"\n/)
    expect(cargoSource).not.toContain('name = "podium-desktop"\npath')
    // rustc derives the crate name from the target name and warns about the
    // capital; the allow is what keeps that from being a build-log surprise.
    expect(mainSource).toContain('#![allow(non_snake_case)]')
  })

  /**
   * POD-1199. ⌘Q used to hang and then be force quit by macOS. Both exit
   * handlers reap the backend child from the MAIN thread, and both lock the
   * child slot to do it — while supervision sat in a blocking `Child::wait()`
   * holding that same lock for the child's whole lifetime. The main thread
   * waited on a lock released only by the child dying, and the only thing that
   * would have killed the child was the main thread.
   *
   * The behaviour is covered by a Rust test (`the_quit_path_can_reap_the_backend
   * _while_supervision_waits`). This pins the shape, because the deadlock is
   * invisible at the call site: it reads as an ordinary wait.
   */
  it('never blocks on the backend while holding the child slot (POD-1199)', () => {
    const between = (from: string, to: string): string => {
      const start = mainSource.indexOf(from)
      const end = mainSource.indexOf(to)
      expect(start, `no ${from} in main.rs`).toBeGreaterThan(-1)
      expect(end, `no ${to} in main.rs`).toBeGreaterThan(start)
      return mainSource.slice(start, end)
    }
    const waiter = between('fn await_child_exit(', '/// Supervise the backend child.')
    // `try_wait` + sleep, never `wait` — the whole point is that the lock is free
    // between checks. (`child.try_wait()` does not contain `child.wait()`.)
    expect(waiter).toContain('child.try_wait()')
    expect(waiter).not.toContain('child.wait()')
    expect(waiter).toContain('std::thread::sleep(poll)')
    // And supervision goes through it rather than waiting on the child itself.
    const monitor = between('fn spawn_respawn_monitor', '/// Best-effort, log-only read')
    expect(monitor).toContain('let Some(exited) = await_child_exit(')
  })

  it('rechecks the watchdog window URL after probing and immediately before navigation', () => {
    const start = mainSource.indexOf('fn spawn_local_document_watchdog(')
    const end = mainSource.indexOf('/// How often supervision checks', start)
    expect(start).toBeGreaterThan(-1)
    expect(end).toBeGreaterThan(start)
    const watchdog = mainSource.slice(start, end)

    const sampled = watchdog.indexOf('let Ok(current) = window.url()')
    const probe = watchdog.indexOf('let healthy = match showing')
    const decision = watchdog.indexOf('let Some(target) = watch.observe')
    const resampled = watchdog.indexOf('let Ok(latest) = window.url()')
    const movedGuard = watchdog.indexOf('if latest != current')
    const navigate = watchdog.indexOf('window.navigate(url)')

    expect(sampled).toBeGreaterThan(-1)
    expect(probe).toBeGreaterThan(sampled)
    expect(decision).toBeGreaterThan(probe)
    expect(resampled).toBeGreaterThan(decision)
    expect(movedGuard).toBeGreaterThan(resampled)
    expect(navigate).toBeGreaterThan(movedGuard)
  })

  it('arms and consumes the bounded watchdog pause for supervised local restarts', () => {
    const watchdogStart = mainSource.indexOf('fn spawn_local_document_watchdog(')
    const watchdogEnd = mainSource.indexOf('/// How often supervision checks', watchdogStart)
    const waiterStart = mainSource.indexOf('fn await_child_exit(')
    const waiterEnd = mainSource.indexOf('/// Supervise the backend child.', waiterStart)
    const monitorStart = mainSource.indexOf('fn spawn_respawn_monitor<')
    const monitorEnd = mainSource.indexOf('/// Best-effort, log-only read', monitorStart)
    const localModeStart = mainSource.indexOf('// Shared local path: stable port')
    const daemonModeStart = mainSource.indexOf(
      'bootstrap::LaunchAction::LocalDaemon',
      localModeStart,
    )

    expect(watchdogStart).toBeGreaterThan(-1)
    expect(watchdogEnd).toBeGreaterThan(watchdogStart)
    expect(waiterStart).toBeGreaterThan(-1)
    expect(waiterEnd).toBeGreaterThan(waiterStart)
    expect(monitorStart).toBeGreaterThan(-1)
    expect(monitorEnd).toBeGreaterThan(monitorStart)
    expect(localModeStart).toBeGreaterThan(-1)
    expect(daemonModeStart).toBeGreaterThan(localModeStart)

    const watchdog = mainSource.slice(watchdogStart, watchdogEnd)
    const waiter = mainSource.slice(waiterStart, waiterEnd)
    const monitor = mainSource.slice(monitorStart, monitorEnd)
    const localMode = mainSource.slice(localModeStart, daemonModeStart)
    const standDown = watchdog.indexOf('if local_restart.is_active()')
    const identityProbe = watchdog.indexOf('bootstrap::probe_local_server(port)', standDown)
    const pauseDecision = watchdog.indexOf(
      'local_restart.should_stand_down(server_ready)',
      identityProbe,
    )
    const ordinaryHealthProbe = watchdog.indexOf('let healthy = match showing')

    expect(standDown).toBeGreaterThan(-1)
    expect(identityProbe).toBeGreaterThan(standDown)
    expect(pauseDecision).toBeGreaterThan(identityProbe)
    expect(ordinaryHealthProbe).toBeGreaterThan(pauseDecision)
    expect(watchdog.slice(pauseDecision, ordinaryHealthProbe)).toContain('continue;')
    expect(waiter).toContain('if handover_started')
    expect(waiter).toContain('local_restart.begin();')
    expect(monitor).toContain('if !intentional_transfer')
    expect(monitor).toContain('observed_pid != paused_exit_pid')
    expect(monitor).toContain('local_restart.begin();')
    expect(mainSource.match(/local_restart\.begin\(\);/g)).toHaveLength(2)
    expect(localMode).toContain('Some(local_restart.clone())')
    expect(mainSource).toContain(
      'spawn_local_document_watchdog(\n                        handle,\n                        port,\n                        watchdog_shutting_down,\n                        local_restart,',
    )
  })
  it('never closes the main window from Cmd+W', () => {
    expect(mainSource).toContain('MenuItemBuilder::with_id("close-tab", "Close Tab")')
    expect(mainSource).toContain('.accelerator("CmdOrCtrl+W")')
    expect(mainSource).not.toContain('MenuItemBuilder::with_id("close-window"')
    expect(mainSource).not.toContain('__PODIUM_DESKTOP__.close()')
    expect(mainSource).toContain('#[cfg(not(target_os = "macos"))]')
    expect(mainSource.match(/MenuItemBuilder::with_id\("close-tab", "Close Tab"\)/g)).toHaveLength(
      2,
    )
  })
  it('uses native traffic lights on macOS and native window-manager chrome elsewhere', () => {
    expect(mainSource).toContain('.title_bar_style(tauri::TitleBarStyle::Overlay)')
    expect(mainSource).toContain('.hidden_title(true)')
    expect(mainSource).toContain('.traffic_light_position(tauri::LogicalPosition::new(14.0, 22.0))')
    expect(mainSource).toContain('const NATIVE_DECORATIONS: bool = true;')
    expect(mainSource).not.toContain('window_builder.decorations(false)')
    expect(mainSource).toContain('.min_inner_size(900.0, 600.0)')
    expect(mainSource).not.toContain('"core:window:allow-minimize"')
    expect(mainSource).not.toContain('"core:window:allow-close"')
    expect(mainSource).not.toContain('"core:window:allow-toggle-maximize"')
  })

  it('creates the window before waiting for a local backend and keeps close-to-hide macOS-only', () => {
    const window = mainSource.indexOf('handle.run_on_main_thread')
    const wait = mainSource.indexOf('bootstrap::wait_for_port', window)
    expect(window).toBeGreaterThan(-1)
    expect(wait).toBeGreaterThan(window)
    expect(mainSource).toContain(
      '#[cfg(target_os = "macos")]\n                tauri::WindowEvent::CloseRequested',
    )
    expect(mainSource).toContain(
      '#[cfg(not(target_os = "macos"))]\n                tauri::WindowEvent::CloseRequested',
    )
    expect(mainSource).toContain('window.app_handle().exit(0);')
    expect(mainSource).not.toContain('TrayIconBuilder')
    const nonMacMenu = mainSource.slice(mainSource.indexOf('// Windows and Linux reserve Ctrl+W'))
    expect(nonMacMenu).not.toContain('.undo()')
    expect(nonMacMenu).not.toContain('.redo()')
    expect(nonMacMenu).not.toContain('.quit()')
    expect(nonMacMenu).not.toContain('.quit_with_text(')
    expect(nonMacMenu).toContain('MenuItemBuilder::with_id("edit-undo", "Undo")')
    expect(nonMacMenu).toContain('MenuItemBuilder::with_id("edit-redo", "Redo")')
    expect(nonMacMenu).toContain('MenuItemBuilder::with_id("quit-app", "Quit Podium ADE")')
  })

  /**
   * POD-1598. Tauri's native drag-drop handler is on by default, and it eats the
   * drag before the document does: while it is installed the webview never sees
   * `dragover`/`drop`, so the composer's file-attach drop zone is dead in the
   * desktop app while working fine in a browser. Nothing in the shell consumes
   * the native events, so the handler is pure loss here.
   *
   * Pinned as source text because this host cannot compile the shell, and
   * because the failure is invisible at the call site — the builder without this
   * call looks complete, and the symptom shows up two layers away in the web app.
   */
  it('lets the page receive HTML5 file drops (POD-1598)', () => {
    const start = mainSource.indexOf('WebviewWindowBuilder::new(&handle2, "main", resolved_url)')
    expect(start, 'no main WebviewWindowBuilder in main.rs').toBeGreaterThan(-1)
    // The chain now continues into the native-open page-load hook. Stop there,
    // not at the first `;`: rationale comments inside the chain contain them.
    const end = mainSource.indexOf('.on_page_load(', start)
    expect(end, 'main window builder chain not found').toBeGreaterThan(start)
    const chain = mainSource.slice(start, end)
    expect(chain).toContain('.disable_drag_drop_handler()')
    // Off on every platform, not just the one Tauri documents: upstream reports
    // put macOS in the same position, and on Linux the handler navigates the
    // webview to the dropped path. A cfg here would re-break two of three.
    expect(chain).not.toContain('#[cfg(')
  })

  it('reveals a native semantic material only through the macOS command bar', () => {
    expect(cargoSource).toContain('"macos-private-api"')
    expect(mainSource).toContain('.transparent(true)')
    // Sidebar, not HeaderView, and the difference is measured rather than a taste
    // call. HeaderView is the semantic pick for a command bar, so it is what the
    // next reader will reach for — but the material composites with the WINDOW's
    // NSAppearance, and in dark mode it lands within ~3% luminance of the opaque
    // bar it replaces (#232628 against --bar #1b1d21). That reads as opaque: the
    // translucency ships, and no one can see it. Sidebar is the visibly
    // translucent chrome material (Finder, Notes) and is what POD-1034's effect
    // was actually for. Swapping back needs a new measurement, not a rename.
    expect(mainSource).toContain('.effect(Effect::Sidebar)')
    expect(mainSource).not.toContain('Effect::HeaderView')
    expect(mainSource).toContain('.state(EffectState::FollowsWindowActiveState)')
    expect(webStyles).toContain(
      'html[data-podium-platform="macos"] .desktop-topbar {\n  background: transparent;',
    )
    expect(webStyles).toContain(
      'html[data-podium-platform="macos"] .desktop-shell-row {\n  background: var(--background);',
    )
  })

  /**
   * POD-2150. `install_update` reports progress by emitting
   * `podium://update-progress`, and the page subscribes with
   * `plugin:event|listen` — which is a PERMISSION, not an ambient capability.
   * The static `default.json` grants only event listen and unlisten, and declares
   * no remote block, so it stops at the local origin. In remote mode the page is
   * served by the remote server, and a shell that lets that page start an
   * install but not hear it report gives the user a spinner that never moves:
   * the one silence the progress events exist to end.
   *
   * Both grants are checked because they are two different lives of the same
   * bridge — startup, and the re-grant after a server transfer — and POD-2150
   * was exactly one of them being forgotten.
   */
  it('lets both update-bridge grants hear the progress event (POD-2150)', () => {
    const grant = (name: string): string => {
      const start = mainSource.indexOf(`CapabilityBuilder::new("${name}")`)
      expect(start, `no ${name} capability in main.rs`).toBeGreaterThan(-1)
      const end = mainSource.indexOf(';', start)
      return mainSource.slice(start, end)
    }
    for (const name of ['update-bridge', 'transfer-update-bridge']) {
      const block = grant(name)
      expect(block, name).toContain('.permission("allow-install-update")')
      expect(block, name).toContain('.permission("core:event:allow-listen")')
      expect(block, name).toContain('.permission("core:event:allow-unlisten")')
    }
  })
})
