/**
 * Writes `src/server-locate.vectors.json`: the shared test vectors for the
 * locate proof (POD-5921). Deterministic — fixed seeds, fixed nonces, and
 * Ed25519 signatures are deterministic — so re-running it reproduces the file
 * byte for byte. The server's signer test, the runtime verifier test and
 * Connect's test (podium-cloud vendors this repository) all read the result.
 *
 *     bun packages/protocol/scripts/generate-server-locate-vectors.ts
 */
import { createPrivateKey, createPublicKey, sign } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { LOCATE_PROOF_PREFIX, locateOrigin, locateProofMessage } from '../src/server-locate'

const PKCS8_ED25519_PREFIX = Buffer.from('302e020100300506032b657004220420', 'hex')

function keyFromSeed(seedByte: number) {
  const seed = Buffer.alloc(32, seedByte)
  const privateKey = createPrivateKey({
    key: Buffer.concat([PKCS8_ED25519_PREFIX, seed]),
    format: 'der',
    type: 'pkcs8',
  })
  const publicKey = createPublicKey(privateKey)
  const raw = publicKey.export({ format: 'jwk' }).x as string
  return {
    privateKey,
    privateKeyPkcs8: privateKey.export({ format: 'der', type: 'pkcs8' }).toString('base64'),
    publicKeySpki: publicKey.export({ format: 'der', type: 'spki' }).toString('base64'),
    installationPublicKey: `ed25519:${raw}`,
  }
}

const installationIdFrom = (byte: number) => `pdm_${Buffer.alloc(32, byte).toString('base64url')}`

const server = { ...keyFromSeed(0x11), installationId: installationIdFrom(0xa1) }
const other = { ...keyFromSeed(0x22), installationId: installationIdFrom(0xb2) }
const nonceA = Buffer.alloc(32, 0x5a)
const nonceB = Buffer.alloc(32, 0x5b)

function answer(signer: typeof server, configuredPublicUrl: string, nonce: Buffer) {
  const publicUrl = locateOrigin(configuredPublicUrl)
  if (!publicUrl) throw new Error(`not a URL: ${configuredPublicUrl}`)
  const message = locateProofMessage(new Uint8Array(nonce), publicUrl)
  return {
    messageHex: Buffer.from(message).toString('hex'),
    response: {
      installationId: signer.installationId,
      publicUrl,
      signature: sign(null, message, signer.privateKey).toString('base64url'),
    },
  }
}

const stored = {
  installationId: server.installationId,
  installationPublicKey: server.installationPublicKey,
}

const cases = [
  {
    name: 'valid',
    configuredPublicUrl: 'https://words-one.trycloudflare.com',
    signedNonce: nonceA,
    nonce: nonceA,
    signer: server,
    serverProduces: true,
    candidate: 'https://words-one.trycloudflare.com',
    stored,
    verdict: 'ok',
  },
  {
    name: 'wrong key',
    configuredPublicUrl: 'https://words-one.trycloudflare.com',
    signedNonce: nonceA,
    nonce: nonceA,
    signer: server,
    serverProduces: true,
    candidate: 'https://words-one.trycloudflare.com',
    stored: {
      installationId: server.installationId,
      installationPublicKey: other.installationPublicKey,
    },
    verdict: 'bad-signature',
  },
  {
    name: 'wrong id',
    configuredPublicUrl: 'https://words-one.trycloudflare.com',
    signedNonce: nonceA,
    nonce: nonceA,
    signer: other,
    serverProduces: false,
    candidate: 'https://words-one.trycloudflare.com',
    stored,
    verdict: 'wrong-id',
  },
  {
    name: 'publicUrl is not the candidate origin',
    configuredPublicUrl: 'https://words-one.trycloudflare.com',
    signedNonce: nonceA,
    nonce: nonceA,
    signer: server,
    serverProduces: true,
    candidate: 'https://relay.example',
    stored,
    verdict: 'origin-mismatch',
  },
  {
    name: 'altered nonce',
    configuredPublicUrl: 'https://words-one.trycloudflare.com',
    signedNonce: nonceA,
    nonce: nonceB,
    signer: server,
    serverProduces: false,
    candidate: 'https://words-one.trycloudflare.com',
    stored,
    verdict: 'bad-signature',
  },
  {
    name: 'trailing-slash publicUrl is normalised',
    configuredPublicUrl: 'https://words-two.trycloudflare.com/',
    signedNonce: nonceA,
    nonce: nonceA,
    signer: server,
    serverProduces: true,
    candidate: 'https://words-two.trycloudflare.com',
    stored,
    verdict: 'ok',
  },
].map(({ signer, signedNonce, nonce, ...rest }) => ({
  ...rest,
  nonce: nonce.toString('base64url'),
  signedNonce: signedNonce.toString('base64url'),
  ...answer(signer, rest.configuredPublicUrl, signedNonce),
}))

const vectors = {
  _comment:
    'Generated by packages/protocol/scripts/generate-server-locate-vectors.ts — do not edit by hand. ' +
    'serverProduces: a server holding `server` and configured with configuredPublicUrl answers a ' +
    'request for `nonce` with exactly `response`. verdict: what a client that sent `nonce` to ' +
    '`candidate` and stored `stored` concludes.',
  prefix: LOCATE_PROOF_PREFIX,
  server: {
    installationId: server.installationId,
    installationPublicKey: server.installationPublicKey,
    privateKeyPkcs8: server.privateKeyPkcs8,
    publicKeySpki: server.publicKeySpki,
  },
  other: {
    installationId: other.installationId,
    installationPublicKey: other.installationPublicKey,
  },
  cases,
}

writeFileSync(
  join(import.meta.dir, '..', 'src', 'server-locate.vectors.json'),
  `${JSON.stringify(vectors, null, 2)}\n`,
)
