// First look: what the TUI shows at start, after one idle prompt, and after a prompt typed while busy.
import { key, kill, launch, screen, sleep, submit, waitLog } from './tui.ts'

launch()
await sleep(4000)
screen('after launch')
await submit('ALPHA idle', 'alpha')
await waitLog('model-requests.jsonl', /ALPHA idle/, 15000)
await sleep(1500)
screen('after ALPHA')
await submit('TOOLSLEEP busy', 'busy')
await waitLog('hooks.jsonl', /PreToolUse/, 15000)
await sleep(500)
await submit('GAMMA typed while busy', 'gamma')
await sleep(700)
screen('after GAMMA Enter')
await submit('DELTA tab while busy', 'delta', 600)
await sleep(300)
screen('before tab')
key('Tab', 'send delta Tab')
await sleep(700)
screen('after DELTA Tab')
await waitLog('hooks.jsonl', /"Stop"/, 30000)
await sleep(3000)
screen('end')
kill()
