/**
 * GENERATED by scripts/harness-descriptors.ts from the adapter registry
 * (presentation in adapters/<harness>/{descriptor,catalog}.ts, client
 * capability flags derived from each harness manifest). Do not hand-edit:
 * change the adapter declaration and re-run the script.
 *
 * Pure literals plus a type-only import — the one shape
 * `@podium/harness/browser` may bundle (POD-4475).
 */
import type { HarnessDescriptorWire } from '@podium/protocol'

export const GENERATED_BUNDLED_DESCRIPTORS: HarnessDescriptorWire[] = 
  [
    {
      "schemaVersion": 1,
      "kind": "claude-code",
      "provider": "anthropic",
      "label": "Claude Code",
      "shortLabel": "Claude",
      "icon": {
        "id": "claude-code",
        "viewBox": "0 0 24 24",
        "d": "M20.998 10.949H24v3.102h-3v3.028h-1.487V20H18v-2.921h-1.487V20H15v-2.921H9V20H7.488v-2.921H6V20H4.487v-2.921H3V14.05H0V10.95h3V5h17.998v5.949zM6 10.949h1.488V8.102H6v2.847zm10.51 0H18V8.102h-1.49v2.847z"
      },
      "brand": {
        "bg": "#d97757",
        "fg": "#ffffff"
      },
      "capabilities": {
        "argvPrompt": true,
        "effort": true,
        "systemPrompt": true
      },
      "catalog": {
        "models": [
          {
            "value": "opus",
            "label": "Opus",
            "efforts": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          },
          {
            "value": "sonnet",
            "label": "Sonnet",
            "efforts": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          },
          {
            "value": "haiku",
            "label": "Haiku",
            "efforts": []
          }
        ],
        "efforts": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ],
        "liveMerge": "live-wins-when-non-empty"
      }
    },
    {
      "schemaVersion": 1,
      "kind": "codex",
      "provider": "openai",
      "label": "Codex",
      "shortLabel": "Codex",
      "icon": {
        "id": "codex",
        "viewBox": "0 0 256 260",
        "d": "M239.184 106.203a64.716 64.716 0 0 0-5.576-53.103C219.452 28.459 191 15.784 163.213 21.74A65.586 65.586 0 0 0 52.096 45.22a64.716 64.716 0 0 0-43.23 31.36c-14.31 24.602-11.061 55.634 8.033 76.74a64.665 64.665 0 0 0 5.525 53.102c14.174 24.65 42.644 37.324 70.446 31.36a64.72 64.72 0 0 0 48.754 21.744c28.481.025 53.714-18.361 62.414-45.481a64.767 64.767 0 0 0 43.229-31.36c14.137-24.558 10.875-55.423-8.083-76.483Zm-97.56 136.338a48.397 48.397 0 0 1-31.105-11.255l1.535-.87 51.67-29.825a8.595 8.595 0 0 0 4.247-7.367v-72.85l21.845 12.636c.218.111.37.32.409.563v60.367c-.056 26.818-21.783 48.545-48.601 48.601Zm-104.466-44.61a48.345 48.345 0 0 1-5.781-32.589l1.534.921 51.722 29.826a8.339 8.339 0 0 0 8.441 0l63.181-36.425v25.221a.87.87 0 0 1-.358.665l-52.335 30.184c-23.257 13.398-52.97 5.431-66.404-17.803ZM23.549 85.38a48.499 48.499 0 0 1 25.58-21.333v61.39a8.288 8.288 0 0 0 4.195 7.316l62.874 36.272-21.845 12.636a.819.819 0 0 1-.767 0L41.353 151.53c-23.211-13.454-31.171-43.144-17.804-66.405v.256Zm179.466 41.695-63.08-36.63L161.73 77.86a.819.819 0 0 1 .768 0l52.233 30.184a48.6 48.6 0 0 1-7.316 87.635v-61.391a8.544 8.544 0 0 0-4.4-7.213Zm21.742-32.69-1.535-.922-51.619-30.081a8.39 8.39 0 0 0-8.492 0L99.98 99.808V74.587a.716.716 0 0 1 .307-.665l52.233-30.133a48.652 48.652 0 0 1 72.236 50.391v.205ZM88.061 139.097l-21.845-12.585a.87.87 0 0 1-.41-.614V65.685a48.652 48.652 0 0 1 79.757-37.346l-1.535.87-51.67 29.825a8.595 8.595 0 0 0-4.246 7.367l-.051 72.697Zm11.868-25.58 28.138-16.217 28.188 16.218v32.434l-28.086 16.218-28.188-16.218-.052-32.434Z"
      },
      "capabilities": {
        "argvPrompt": true,
        "effort": true,
        "systemPrompt": false
      },
      "catalog": {
        "models": [
          {
            "value": "gpt-5.6-sol",
            "label": "GPT-5.6-Sol",
            "efforts": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max",
              "ultra"
            ]
          },
          {
            "value": "gpt-5.6-terra",
            "label": "GPT-5.6-Terra",
            "efforts": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max",
              "ultra"
            ]
          },
          {
            "value": "gpt-5.6-luna",
            "label": "GPT-5.6-Luna",
            "efforts": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ]
          },
          {
            "value": "gpt-5.5",
            "label": "GPT-5.5",
            "efforts": [
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          },
          {
            "value": "gpt-5.4",
            "label": "GPT-5.4",
            "efforts": [
              "low",
              "medium",
              "high",
              "xhigh"
            ]
          }
        ],
        "efforts": [
          "low",
          "medium",
          "high",
          "xhigh"
        ],
        "liveMerge": "live-wins-when-non-empty"
      }
    },
    {
      "schemaVersion": 1,
      "kind": "grok",
      "provider": "xai",
      "label": "Grok",
      "shortLabel": "Grok",
      "icon": {
        "id": "grok",
        "viewBox": "0 0 24 24",
        "d": "M9.27 15.29l7.978-5.897c.391-.29.95-.177 1.137.272.98 2.369.542 5.215-1.41 7.169-1.951 1.954-4.667 2.382-7.149 1.406l-2.711 1.257c3.889 2.661 8.611 2.003 11.562-.953 2.341-2.344 3.066-5.539 2.388-8.42l.006.007c-.983-4.232.242-5.924 2.75-9.383.06-.082.12-.164.179-.248l-3.301 3.305v-.01L9.267 15.292M7.623 16.723c-2.792-2.67-2.31-6.801.071-9.184 1.761-1.763 4.647-2.483 7.166-1.425l2.705-1.25a7.808 7.808 0 00-1.829-1A8.975 8.975 0 005.984 5.83c-2.533 2.536-3.33 6.436-1.962 9.764 1.022 2.487-.653 4.246-2.34 6.022-.599.63-1.199 1.259-1.682 1.925l7.62-6.815"
      },
      "brand": {
        "bg": "#ffffff",
        "fg": "#09090b"
      },
      "capabilities": {
        "argvPrompt": true,
        "effort": true,
        "systemPrompt": false
      },
      "catalog": {
        "models": [
          {
            "value": "grok-4.5",
            "label": "Grok 4.5"
          },
          {
            "value": "grok-composer-2.5-fast",
            "label": "Composer 2.5 Fast"
          }
        ],
        "efforts": [
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ],
        "liveMerge": "live-wins-when-non-empty"
      }
    },
    {
      "schemaVersion": 1,
      "kind": "opencode",
      "provider": "opencode",
      "label": "OpenCode",
      "shortLabel": "OpenCode",
      "icon": {
        "id": "opencode",
        "viewBox": "0 0 24 24",
        "d": "M16 6H8v12h8V6zm4 16H4V2h16v20z"
      },
      "capabilities": {
        "argvPrompt": true,
        "effort": true,
        "systemPrompt": false
      },
      "catalog": {
        "models": [
          {
            "value": "openai/gpt-5.5",
            "label": "OpenAI GPT-5.5"
          },
          {
            "value": "anthropic/claude-opus-4-8",
            "label": "Claude Opus 4.8"
          },
          {
            "value": "xai/grok-4.3",
            "label": "Grok 4.3"
          }
        ],
        "efforts": [
          "minimal",
          "low",
          "medium",
          "high",
          "max"
        ],
        "liveMerge": "live-wins-when-non-empty"
      },
      "login": {
        "command": "opencode auth login",
        "installHint": "Install OpenCode on this machine, then run “opencode auth login”. Podium will detect it automatically.",
        "signedOutHint": "Installed but not signed in. You can continue now and sign in before you run it."
      }
    },
    {
      "schemaVersion": 1,
      "kind": "cursor",
      "provider": "cursor",
      "label": "Cursor",
      "shortLabel": "Cursor",
      "icon": {
        "id": "cursor",
        "viewBox": "0 0 24 24",
        "d": "M11.503.131 1.891 5.678a.84.84 0 0 0-.42.726v11.188c0 .3.162.575.42.724l9.609 5.55a1 1 0 0 0 .998 0l9.61-5.55a.84.84 0 0 0 .42-.724V6.404a.84.84 0 0 0-.42-.726L12.497.131a1.01 1.01 0 0 0-.996 0M2.657 6.338h18.55c.263 0 .43.287.297.515L12.23 22.918c-.062.107-.229.064-.229-.06V12.335a.59.59 0 0 0-.295-.51l-9.11-5.257c-.109-.063-.064-.23.061-.23"
      },
      "capabilities": {
        "argvPrompt": false,
        "effort": false,
        "systemPrompt": false
      },
      "catalog": {
        "models": [
          {
            "value": "composer-2.5",
            "label": "Composer 2.5"
          },
          {
            "value": "gpt-5.2",
            "label": "GPT-5.2"
          },
          {
            "value": "claude-opus-4-8-thinking-high",
            "label": "Claude Opus 4.8 Thinking"
          }
        ],
        "efforts": [],
        "liveMerge": "live-wins-when-non-empty"
      },
      "login": {
        "command": "cursor-agent login"
      }
    },
    {
      "schemaVersion": 1,
      "kind": "pi",
      "provider": "pi",
      "label": "Pi",
      "shortLabel": "Pi",
      "icon": {
        "id": "pi",
        "viewBox": "0 0 24 24",
        "d": "M3.5 5.5h17V8h-2.75v10.5h-2.5V8h-6.5v10.5h-2.5V8H3.5z"
      },
      "capabilities": {
        "argvPrompt": true,
        "effort": true,
        "systemPrompt": true
      },
      "catalog": {
        "models": [],
        "efforts": [
          "off",
          "minimal",
          "low",
          "medium",
          "high",
          "xhigh",
          "max"
        ],
        "liveMerge": "live-wins-when-non-empty"
      },
      "login": {
        "command": "pi",
        "installHint": "Install Pi on this machine, then run “pi” and sign in with its /login command. Podium will detect it automatically."
      }
    }
  ]
