import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#101114', paddingTop: 56 },
  header: {
    paddingHorizontal: 18,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: { color: '#f8fafc', fontSize: 30, fontWeight: '700' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#20242c',
  },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  dot: { width: 8, height: 8, borderRadius: 4 },
  dotOk: { backgroundColor: '#22c55e' },
  dotDown: { backgroundColor: '#ef4444' },
  statusText: { color: '#cbd5e1', fontSize: 13 },
  notice: {
    marginHorizontal: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#4b3f13',
    backgroundColor: '#221d0d',
    borderRadius: 8,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  noticeText: { color: '#fde68a', flex: 1, fontSize: 13 },
  list: { paddingHorizontal: 14, paddingBottom: 32, gap: 10 },
  card: {
    minHeight: 104,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2f333a',
    backgroundColor: '#181a20',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  cardNeedsYou: { borderColor: '#c08412', backgroundColor: '#201b12' },
  cardMain: { flex: 1, gap: 4 },
  cardTitle: { color: '#f8fafc', fontSize: 16, fontWeight: '700' },
  cardMeta: { color: '#94a3b8', fontSize: 12 },
  issue: { color: '#93c5fd', fontSize: 13 },
  summary: { color: '#facc15', fontSize: 13, lineHeight: 18 },
  empty: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2f333a',
    backgroundColor: '#181a20',
    padding: 18,
  },
  emptyTitle: { color: '#f8fafc', fontSize: 17, fontWeight: '700', marginBottom: 6 },
  emptyText: { color: '#94a3b8', fontSize: 14, lineHeight: 20 },
})
