/**
 * Browser runtime model surface.
 *
 * Audit registries, ownership-matrix data, arbitration policy, and retained-
 * representation checks intentionally remain on the package root only.
 */

export * from './entities/agent'
export * from './entities/automation'
export * from './entities/conversation'
export * from './entities/cost'
export * from './entities/draft-doc'
export * from './entities/issue'
export * from './entities/issue-color'
export * from './entities/issue-git-state'
export * from './entities/issue-status'
export * from './entities/machine'
export * from './entities/machine-projection'
export * from './entities/session'
export * from './entities/transcript'
export * from './entities/wire-input'
export * from './fields/attribution'
export * from './identity/git-identity'
export * from './identity/user'
export * from './ids'
export * from './machine-path'
export * from './predicates/active-work'
export * from './predicates/agent-computing'
export * from './predicates/idle-verdict'
export { isClosed, isExcluded, isFinished } from './predicates/issue-lifecycle'
export * from './predicates/issue-stage'
export * from './predicates/machine-capability'
export * from './predicates/machine-handoff'
export * from './predicates/machine-selection'
export * from './predicates/mobile-entry'
export * from './predicates/snooze'
export * from './predicates/stopped-send'
export * from './predicates/unaddressable-send'
export * from './settings/path-tiers'
export * from './settings/secrets'
export * from './user-state/issue-state'
export * from './user-state/layout-state'
