import type { AndroidSymbol, SFSymbol, SymbolViewProps } from 'expo-symbols'

export type AppIcon = SymbolViewProps['name']

/**
 * One semantic icon vocabulary for the phone chrome. iOS renders the SF Symbol
 * while Android and web render the matching Material Symbol through
 * `expo-symbols`.
 */
function symbol(ios: SFSymbol, material: AndroidSymbol): AppIcon {
  return { ios, android: material, web: material }
}

export const Activity = symbol('waveform.path.ecg', 'activity_zone')
export const AlarmClock = symbol('alarm', 'alarm')
export const AlertTriangle = symbol('exclamationmark.triangle', 'warning')
export const ArrowDown = symbol('arrow.down', 'arrow_downward')
export const ArrowDownToLine = symbol('arrow.down.to.line', 'file_download')
export const ArrowRight = symbol('arrow.right', 'arrow_forward')
export const ArrowUp = symbol('arrow.up', 'arrow_upward')
export const Check = symbol('checkmark', 'check')
export const CheckCircle2 = symbol('checkmark.circle', 'check_circle')
export const ChevronDown = symbol('chevron.down', 'expand_more')
export const ChevronLeft = symbol('chevron.left', 'chevron_left')
export const ChevronRight = symbol('chevron.right', 'chevron_right')
export const ChevronUp = symbol('chevron.up', 'expand_less')
export const ChevronsDownUp = symbol('arrow.down.and.line.horizontal.and.arrow.up', 'unfold_less')
export const ChevronsUpDown = symbol('arrow.up.and.line.horizontal.and.arrow.down', 'unfold_more')
export const Circle = symbol('circle', 'circle')
export const CircleDot = symbol('smallcircle.circle', 'radio_button_checked')
export const ClipboardPaste = symbol('document.on.clipboard', 'content_paste')
export const Cpu = symbol('cpu', 'memory')
export const Eraser = symbol('eraser', 'ink_eraser')
export const ExternalLink = symbol('arrow.up.right.square', 'open_in_new')
export const FileText = symbol('doc.text', 'description')
export const Filter = symbol('line.3.horizontal.decrease.circle', 'filter_list')
export const Flag = symbol('flag', 'flag')
export const FlagOff = symbol('flag.slash', 'outlined_flag')
export const Gauge = symbol('gauge.with.dots.needle.33percent', 'speed')
export const GitBranch = symbol('arrow.triangle.branch', 'account_tree')
export const GitCommit = symbol('smallcircle.circle', 'commit')
export const GitMerge = symbol('arrow.triangle.merge', 'merge')
export const Globe = symbol('globe', 'public')
export const Inbox = symbol('tray', 'inbox')
export const Image = symbol('photo', 'image')
export const KanbanSquare = symbol('rectangle.3.group', 'view_kanban')
export const Layers = symbol('square.3.layers.3d', 'layers')
export const Lightbulb = symbol('lightbulb', 'lightbulb')
export const Link2 = symbol('link', 'link')
export const Mail = symbol('envelope', 'mail')
export const Maximize2 = symbol('arrow.up.left.and.arrow.down.right', 'fullscreen')
export const MessageCircleQuestion = symbol('questionmark.bubble', 'help')
export const MessagesSquare = symbol('bubble.left.and.bubble.right', 'forum')
export const Mic = symbol('mic', 'mic')
export const MicOff = symbol('mic.slash', 'mic_off')
export const Monitor = symbol('display', 'monitor')
export const Moon = symbol('moon', 'nightlight')
export const MoreHorizontal = symbol('ellipsis', 'more_horiz')
export const MoreVertical = symbol('ellipsis', 'more_vert')
export const Paperclip = symbol('paperclip', 'attach_file')
export const Pencil = symbol('pencil', 'edit')
export const Pin = symbol('pin', 'push_pin')
export const Play = symbol('play', 'play_arrow')
export const Plus = symbol('plus', 'add')
export const RefreshCw = symbol('arrow.clockwise', 'refresh')
export const RotateCcw = symbol('arrow.counterclockwise', 'restart_alt')
export const Rows3 = symbol('rectangle.split.3x1', 'table_rows')
export const Search = symbol('magnifyingglass', 'search')
export const Settings = symbol('gearshape', 'settings')
export const SkipForward = symbol('forward.end', 'skip_next')
export const Smartphone = symbol('iphone', 'smartphone')
export const Square = symbol('stop', 'stop')
export const SquareTerminal = symbol('terminal', 'terminal')
export const Trash2 = symbol('trash', 'delete')
export const Unlock = symbol('lock.open', 'lock_open')
export const Users = symbol('person.2', 'group')
export const X = symbol('xmark', 'close')
