/**
 * Regenerates `apps/server/src/migrations/drizzle-manifest.generated.ts` from the
 * drizzle-kit migration folders under `apps/server/src/migrations/drizzle/`.
 *
 * WHY a generated module of inlined strings: the runtime applier
 * (drizzle-runner.ts) must NOT read migration files from disk — the
 * `bun --compile` single binary carries no `drizzle/` folder. Inlining each
 * `migration.sql` as a JSON-escaped string literal makes the migrations bundle
 * into the binary and load identically under Bun and Node. `migration:new`
 * regenerates this, and CI checks it is not stale (`--check`).
 *
 * Usage: `bun run scripts/build-drizzle-manifest.ts [--check]`
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '..')
const DRIZZLE_DIR = join(REPO, 'apps/server/src/migrations/drizzle')
const OUT = join(REPO, 'apps/server/src/migrations/drizzle-manifest.generated.ts')

/** Migration folders in name order — the timestamp prefix makes this chronological. */
function migrationFolders(): string[] {
  return readdirSync(DRIZZLE_DIR)
    .filter((name) => {
      const full = join(DRIZZLE_DIR, name)
      return statSync(full).isDirectory()
    })
    .sort((a, b) => a.localeCompare(b))
}

function render(): string {
  const folders = migrationFolders()
  if (folders.length === 0) {
    throw new Error(`no migration folders found under ${DRIZZLE_DIR}`)
  }
  if (!/_baseline$/.test(folders[0])) {
    throw new Error(
      `the first migration must be the baseline (folder name ending in '_baseline'); ` +
        `got '${folders[0]}'. The baseline is stamped (not run) on existing databases, ` +
        `so it must sort first.`,
    )
  }
  const entries = folders.map((name) => {
    const sql = readFileSync(join(DRIZZLE_DIR, name, 'migration.sql'), 'utf8')
    return `  { name: ${JSON.stringify(name)}, sql: ${JSON.stringify(sql)} },`
  })
  return `// GENERATED by scripts/build-drizzle-manifest.ts — do not edit by hand.
// Regenerate with \`bun run migration:new\` or \`bun run scripts/build-drizzle-manifest.ts\`.
import type { DrizzleMigration } from './index'

/** All drizzle migrations, bundled as strings, in chronological (name) order. */
export const DRIZZLE_MIGRATIONS: DrizzleMigration[] = [
${entries.join('\n')}
]

/**
 * The baseline — the verbatim dump of the schema as it stood when drizzle was
 * adopted. On an existing (legacy) database this is STAMPED, not executed,
 * because the legacy chain already built that schema [spec:SP-4428].
 */
export const BASELINE_MIGRATION: DrizzleMigration = DRIZZLE_MIGRATIONS[0]!
`
}

const content = render()
if (process.argv.includes('--check')) {
  const current = (() => {
    try {
      return readFileSync(OUT, 'utf8')
    } catch {
      return ''
    }
  })()
  if (current !== content) {
    console.error(
      `drizzle-manifest.generated.ts is stale. Run \`bun run scripts/build-drizzle-manifest.ts\`.`,
    )
    process.exit(1)
  }
  console.log('drizzle-manifest.generated.ts is up to date.')
} else {
  writeFileSync(OUT, content)
  console.log(`wrote ${OUT}`)
}
