#!/usr/bin/env bun
/**
 * harness-matrix — generate docs/architecture/harness-support-matrix.md (POD-4474).
 *
 * The matrix is a PROJECTION of the registry, not a second opinion about it:
 * every cell reads `sectionStatusesOf(manifest)` from `@podium/harness`, so a
 * harness that grows a section updates the document with no second edit. The
 * check runs the decline-reason gate first, so a placeholder reason refuses
 * the matrix before it refuses the commit.
 *
 *   bun --conditions=@podium/source scripts/harness-matrix.ts          rewrite the page
 *   bun --conditions=@podium/source scripts/harness-matrix.ts --check  fail if it is stale (CI)
 *
 * Spec §4.7: this page is the FIRST of the three capability inputs
 * (implemented / available-on-this-machine / effective-for-this-session) and
 * is never presented as a session's capability. The served descriptor derives
 * its "implemented" flags from the same `sectionStatusesOf` rows this page
 * renders — the programmatic input lives in the registry, the page is the
 * human review surface.
 */

import { writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  AGENT_MANIFESTS,
  assertDeclinedReasonsValid,
  sectionStatusesOf,
  type AgentManifest,
} from '@podium/harness'
import { BUILTIN_HARNESS_KINDS } from '@podium/protocol'

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(REPO, 'docs', 'architecture', 'harness-support-matrix.md')

/** Column order DERIVED from the closed harness set, never hand-listed: a
 * seventh harness appears in the matrix with no edit here (POD-4476 — harness
 * names are defined once and derived everywhere, so this file holds no
 * harness literals of its own). */
const HARNESS_ORDER = BUILTIN_HARNESS_KINDS

function render(manifests: Record<string, AgentManifest>): string {
  const kinds = HARNESS_ORDER.filter((kind) => manifests[kind])
  // The UNION of sections across harnesses: nested rows (usage.quota, …)
  // exist only where the parent is supported, so the first harness's rows
  // alone are not the full section set. First-appearance order keeps the
  // output deterministic.
  const seen = new Set<string>()
  const sections: string[] = []
  for (const kind of kinds) {
    for (const row of sectionStatusesOf(manifests[kind] as AgentManifest)) {
      if (!seen.has(row.section)) {
        seen.add(row.section)
        sections.push(row.section)
      }
    }
  }
  const statusOf = (kind: string, section: string): { supported: boolean; reason?: string } => {
    const found = sectionStatusesOf(manifests[kind] as AgentManifest).find(
      (row) => row.section === section,
    )
    // No row means the parent section is declined, which declines the child
    // with it — report the parent's reason rather than inventing a cell.
    if (!found) {
      const parent = section.split('.').slice(0, -1).join('.')
      const parentRow = sectionStatusesOf(manifests[kind] as AgentManifest).find(
        (row) => row.section === parent,
      )
      return {
        supported: false,
        reason: parentRow && !parentRow.supported ? `(via ${parent}) ${parentRow.reason}` : undefined,
      }
    }
    return found
  }

  const lines: string[] = []
  lines.push('# Harness support matrix')
  lines.push('')
  lines.push(
    '<!-- GENERATED by scripts/harness-matrix.ts from the adapter registry. Do not hand-edit: ' +
      'change the adapter declaration and re-run the script. -->',
  )
  lines.push('')
  lines.push(
    'Spec §4.7: this page is the FIRST of the three capability inputs — what the ' +
      'adapter declares as implemented. It is never a session\'s capability on its own: ' +
      'whether this machine can provide it (inventory + admission) and what this session ' +
      'can do now (the selected driver\'s live handle) are answered separately. ' +
      'The served descriptor derives its "implemented" flags from the same registry rows ' +
      'this page renders (`sectionStatusesOf` in `packages/harness/src/registry.ts`).',
  )
  lines.push('')
  lines.push(
    'The `descriptor` and `catalog` Adapter sections (spec §4.1/§4.5) are NOT rows ' +
      'above: they are plain required `AgentManifest` fields — never `Declared`, never ' +
      'declined, so there is nothing to walk — and their totality is a typecheck, not a ' +
      'cell. A harness without presentation cannot be offered.',
  )
  lines.push('')
  lines.push('## Supported / declined by section')
  lines.push('')
  lines.push(`| section | ${kinds.join(' | ')} |`)
  lines.push(`| --- | ${kinds.map(() => '---').join(' | ')} |`)
  for (const section of sections) {
    const cells = kinds.map((kind) =>
      statusOf(kind, section).supported ? 'supported' : 'declined',
    )
    lines.push(`| \`${section}\` | ${cells.join(' | ')} |`)
  }
  lines.push('')
  for (const kind of kinds) {
    const rows = sectionStatusesOf(manifests[kind] as AgentManifest)
    const declined = rows.filter((row) => !row.supported)
    const supportedCount = rows.length - declined.length
    lines.push(`## ${kind} — supported ${supportedCount}/${rows.length}`)
    lines.push('')
    if (declined.length === 0) {
      lines.push('Declines nothing.');
      lines.push('')
      continue
    }
    for (const row of declined) {
      lines.push(`- \`${row.section}\`: ${row.reason}`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

const check = process.argv.includes('--check')
assertDeclinedReasonsValid(AGENT_MANIFESTS)
const { readFileSync } = await import('node:fs')
const next = render(AGENT_MANIFESTS)
if (check) {
  const current = readFileSync(OUT, 'utf8')
  if (current !== next) {
    console.error(`stale: ${OUT} differs from the registry — run the generator and commit it`)
    process.exit(1)
  }
  console.log('harness support matrix is current')
} else {
  writeFileSync(OUT, next)
  console.log(`wrote ${OUT}`)
}
