#!/usr/bin/env bun
/**
 * harness-descriptors — generate the bundled descriptor snapshot (POD-4475).
 *
 * The snapshot is a PROJECTION of the registry, not a second opinion about
 * it: every row joins the hand-written presentation in
 * `adapters/<harness>/{descriptor,catalog}.ts` with the client capability
 * flags DERIVED from that harness's manifest (`buildBundledDescriptors` in
 * `@podium/harness`), so a manifest that flips a flag updates the snapshot
 * with no second edit. The check refuses a stale file (CI), exactly like
 * `scripts/harness-matrix.ts` and `docs:harness-matrix:check` (POD-4474).
 *
 *   bun --conditions=@podium/source scripts/harness-descriptors.ts          rewrite the snapshot
 *   bun --conditions=@podium/source scripts/harness-descriptors.ts --check  fail if it is stale (CI)
 *
 * WHY GENERATED, NOT STATED + TESTED. A stated snapshot with an equality
 * test is two hand-maintained things agreeing — POD-4518's defect class,
 * where a hand-written list silently stopped matching the registry while the
 * check kept reporting green. Generation makes drift impossible rather than
 * merely detected.
 *
 * The output lives under `adapters/` (inside the vendor-behaviour home, so
 * its harness literals are legal) and is pure literals plus a type-only
 * import — the one shape `@podium/harness/browser` may bundle without
 * pulling the manifests, the transcript grammars, or sqlite.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { assertDeclinedReasonsValid, AGENT_MANIFESTS, buildBundledDescriptors } from '@podium/harness'

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(REPO, 'packages', 'harness', 'src', 'adapters', 'bundled-descriptors.generated.ts')

function render(): string {
  const rows = buildBundledDescriptors()
  const lines: string[] = []
  lines.push('/**')
  lines.push(' * GENERATED by scripts/harness-descriptors.ts from the adapter registry')
  lines.push(' * (presentation in adapters/<harness>/{descriptor,catalog}.ts, client')
  lines.push(' * capability flags derived from each harness manifest). Do not hand-edit:')
  lines.push(' * change the adapter declaration and re-run the script.')
  lines.push(' *')
  lines.push(' * Pure literals plus a type-only import — the one shape')
  lines.push(' * `@podium/harness/browser` may bundle (POD-4475).')
  lines.push(' */')
  lines.push("import type { HarnessDescriptorWire } from '@podium/protocol'")
  lines.push('')
  lines.push('export const GENERATED_BUNDLED_DESCRIPTORS: HarnessDescriptorWire[] = ')
  lines.push(`  ${JSON.stringify(rows, null, 2).replace(/\n/g, '\n  ')}`)
  lines.push('')
  return lines.join('\n')
}

const check = process.argv.includes('--check')
assertDeclinedReasonsValid(AGENT_MANIFESTS)
const next = render()
if (check) {
  const current = readFileSync(OUT, 'utf8')
  if (current !== next) {
    console.error(
      'harness descriptors snapshot is stale: re-run `bun run harness:descriptors` ' +
        'and commit the result (POD-4475).',
    )
    process.exit(1)
  }
} else {
  writeFileSync(OUT, next)
}
