import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { REACTIONS } from '../apps/server/src/composition/reactions'

const REPO = resolve(import.meta.dirname, '..')
const OUTPUT = resolve(REPO, 'docs/architecture/reactions-ledger.md')

const cell = (value: string): string => value.replaceAll('|', '\\|').replaceAll('\n', ' ')

export function renderReactionsLedger(): string {
  const rows = REACTIONS.map((reaction) => {
    const replay =
      reaction.replay.mode === 'none'
        ? `none — ${reaction.replay.reason}`
        : `startup reconcile from ${reaction.replay.sourceOfTruth}; re-authorize at apply`
    const principal =
      reaction.principal.class === 'system'
        ? 'system; actor=system; scope=acted-on entity'
        : 'delegated; live delegation; re-authorize at apply'
    return `| \`${reaction.id}\` | ${cell(reaction.trigger)} | ${reaction.durability} | ${cell(replay)} | ${cell(`${reaction.idempotency.key} (${reaction.idempotency.duplicatePolicy})`)} | ${cell(reaction.ordering)} | ${cell(`${reaction.retry} Owner: ${reaction.failureOwner}`)} | ${cell(principal)} | ${cell(reaction.scopeInvariant)} | ${cell([...reaction.observability.events, ...reaction.observability.metrics].join(', ') || 'registry only')} |`
  })
  return [
    '# Reactions ledger',
    '',
    '> Generated by `bun scripts/reactions-ledger.ts --write`; checked without `--write`.',
    '> The typed source of truth is `apps/server/src/composition/reactions.ts`.',
    '',
    'A reaction is admitted only for a semantically asynchronous effect. Atomic caller workflows live in application orchestrators and are documented separately.',
    '',
    '| Reaction | Trigger | Durability | Restart replay | Idempotency | Ordering | Retry / failure owner | Principal | Scope invariant | Observability |',
    '|---|---|---|---|---|---|---|---|---|---|',
    ...rows,
    '',
    '## Startup reconciliation',
    '',
    'Every durable entry names its durable source of truth above. Reconciliation re-reads that source, derives pending work, and re-authorizes the declared system scope or live delegation before each apply; persisted effective capabilities are never trusted.',
    '',
  ].join('\n')
}

function main(): void {
  const content = renderReactionsLedger()
  if (process.argv.includes('--write')) {
    mkdirSync(dirname(OUTPUT), { recursive: true })
    writeFileSync(OUTPUT, content)
    console.log(`wrote ${relative(REPO, OUTPUT)}`)
  } else if (!existsSync(OUTPUT) || readFileSync(OUTPUT, 'utf8') !== content) {
    throw new Error('reactions ledger is missing or stale; run with --write')
  } else {
    console.log(`reactions ledger is current (${REACTIONS.length} reactions)`)
  }
}

if (import.meta.main) main()
