import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import ts from 'typescript'

const REPO = resolve(import.meta.dirname, '..')
const ROOT = resolve(REPO, 'apps/server/src/relay.ts')
const OUTPUT = resolve(REPO, 'docs/architecture/server-composition-graph.md')

export interface ImportGraph {
  nodes: string[]
  edges: Map<string, string[]>
}

function resolveImport(from: string, specifier: string): string | undefined {
  if (!specifier.startsWith('.')) return undefined
  const base = resolve(dirname(from), specifier)
  return [`${base}.ts`, resolve(base, 'index.ts')].find(existsSync)
}

function runtimeImports(path: string): string[] {
  const source = ts.createSourceFile(
    path,
    readFileSync(path, 'utf8'),
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  )
  const imports: string[] = []
  for (const statement of source.statements) {
    if (!ts.isImportDeclaration(statement) || statement.importClause?.isTypeOnly) continue
    if (!ts.isStringLiteral(statement.moduleSpecifier)) continue
    const target = resolveImport(path, statement.moduleSpecifier.text)
    if (target) imports.push(target)
  }
  return [...new Set(imports)].sort()
}

export function compositionImportGraph(root = ROOT): ImportGraph {
  const edges = new Map<string, string[]>()
  const visit = (path: string): void => {
    if (edges.has(path)) return
    const imports = runtimeImports(path)
    edges.set(path, imports)
    for (const imported of imports) visit(imported)
  }
  visit(root)
  return { nodes: [...edges.keys()].sort(), edges }
}

export function topologicalModules(graph: ImportGraph): string[] {
  const state = new Map<string, 'visiting' | 'done'>()
  const stack: string[] = []
  const order: string[] = []
  const visit = (node: string): void => {
    if (state.get(node) === 'done') return
    if (state.get(node) === 'visiting') {
      const cycle = [...stack.slice(stack.indexOf(node)), node].map((path) => relative(REPO, path))
      throw new Error(`runtime import cycle: ${cycle.join(' -> ')}`)
    }
    state.set(node, 'visiting')
    stack.push(node)
    for (const dependency of graph.edges.get(node) ?? []) visit(dependency)
    stack.pop()
    state.set(node, 'done')
    order.push(node)
  }
  for (const node of graph.nodes) visit(node)
  return order
}

function render(graph: ImportGraph, order: string[]): string {
  const local = (path: string): string => relative(REPO, path)
  const edgeCount = [...graph.edges.values()].reduce((sum, rows) => sum + rows.length, 0)
  return [
    '# Server composition import graph',
    '',
    '> Generated by `bun scripts/server-composition-graph.ts --write`; checked without `--write`.',
    '> Type-only imports are excluded because they produce no runtime module edge.',
    '',
    `Root: \`${local(ROOT)}\``,
    '',
    `Runtime modules: ${graph.nodes.length}. Runtime edges: ${edgeCount}. Cycles: 0.`,
    '',
    '## Verified topological order',
    '',
    ...order.map((path, index) => `${index + 1}. \`${local(path)}\``),
    '',
    '## Import edges',
    '',
    '| Importer | Runtime dependencies |',
    '|---|---|',
    ...graph.nodes.map((node) => {
      const dependencies = graph.edges.get(node) ?? []
      const rendered = dependencies.length
        ? dependencies.map((path) => `\`${local(path)}\``).join('<br>')
        : '—'
      return `| \`${local(node)}\` | ${rendered} |`
    }),
    '',
  ].join('\n')
}

function main(): void {
  const graph = compositionImportGraph()
  const content = render(graph, topologicalModules(graph))
  if (process.argv.includes('--write')) {
    mkdirSync(dirname(OUTPUT), { recursive: true })
    writeFileSync(OUTPUT, content)
    console.log(`wrote ${relative(REPO, OUTPUT)}`)
  } else if (!existsSync(OUTPUT) || readFileSync(OUTPUT, 'utf8') !== content) {
    throw new Error('composition graph is missing or stale; run with --write')
  } else {
    console.log(`composition graph is acyclic and current (${graph.nodes.length} modules)`)
  }
}

if (import.meta.main) main()
