/**
 * Diff the checked-in dev-host outputs against the source renderer.
 *
 * `scripts/render-systemd.ts` is intentionally a writer. This focused check gives generated
 * outputs a stable build/lint gate without parsing install.sh or extracting a heredoc.
 */
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { renderSystemdFiles } from '../apps/cli/src/cli-systemd'

const root = fileURLToPath(new URL('..', import.meta.url))
const dir = join(root, 'scripts/systemd')
const rendered = renderSystemdFiles({ profile: 'dev', instanceId: 'default' })
const problems: string[] = []
const expectedNames = new Set(Object.keys(rendered.units))

for (const name of readdirSync(dir)) {
  if (/\.(service|timer|path|socket)$/.test(name) && !expectedNames.has(name)) {
    problems.push(`${name}: unexpected generated unit file`)
  }
}

for (const [name, expected] of Object.entries(rendered.units)) {
  const path = join(dir, name)
  let actual: string
  try {
    actual = readFileSync(path, 'utf8')
  } catch {
    problems.push(`${name}: missing generated file`)
    continue
  }
  if (actual !== expected) problems.push(`${name}: generated bytes differ from cli-systemd.ts`)
}

if (rendered.healthProbe) {
  const path = join(root, 'scripts/podium-health-probe.sh')
  let actual: string
  try {
    actual = readFileSync(path, 'utf8')
  } catch {
    actual = ''
  }
  if (actual !== rendered.healthProbe)
    problems.push('scripts/podium-health-probe.sh: generated bytes differ from cli-systemd.ts')
}

if (problems.length) {
  console.error('systemd-diff: generated dev-host outputs are stale:')
  for (const problem of problems) console.error(`  ${problem}`)
  console.error('Run `bun run systemd:render` and review the generated diff.')
  process.exit(1)
}

console.log(
  `systemd-diff: ${Object.keys(rendered.units).length + 1} generated dev-host files match`,
)
