#!/usr/bin/env bun
/**
 * Regenerate the golden wire fixtures (POD-360).
 *
 *     bun run fixtures:wire:update
 *
 * Then READ THE DIFF. That is the entire workflow: the fixtures are a
 * characterization suite, so a change in them is never "the test is stale" — it
 * is the wire moving, and the diff says how. `wire` lines that only APPEAR are
 * an additive change (what POD-1075 and POD-1076 are required to be); `wire`
 * lines that CHANGE in place, or a moved `encoded` string under an unchanged
 * `wire`, are not.
 */

import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { buildCorpus, serializeFamily } from '../packages/protocol/src/__fixtures__/build'
import { buildFeatureStateGolden } from '../packages/protocol/src/__fixtures__/feature-state'

const GOLDEN_DIR = join(
  import.meta.dirname,
  '..',
  'packages',
  'protocol',
  'src',
  '__fixtures__',
  'golden',
)

mkdirSync(GOLDEN_DIR, { recursive: true })

const corpus = buildCorpus()
const written = new Set(corpus.map((family) => `${family.family}.json`))

for (const family of corpus) {
  writeFileSync(join(GOLDEN_DIR, `${family.family}.json`), serializeFamily(family))
}

// FeatureState is not a zod schema, so it is built separately — see
// __fixtures__/feature-state.ts for why it would otherwise be the one gap in
// "every message family".
const featureState = buildFeatureStateGolden()
written.add(`${featureState.family}.json`)
writeFileSync(
  join(GOLDEN_DIR, `${featureState.family}.json`),
  `${JSON.stringify(featureState, null, 2)}\n`,
)

// A family whose module was deleted must lose its golden file too, or the
// corpus and the committed fixtures disagree in a direction no test looks at.
for (const existing of readdirSync(GOLDEN_DIR)) {
  if (existing.endsWith('.json') && !written.has(existing)) {
    rmSync(join(GOLDEN_DIR, existing))
    console.log(`removed stale golden ${existing}`)
  }
}

// A generated static-import index, because `packages/protocol` is a LEAF: its
// tsconfig sets `types: []`, so the suite cannot read the corpus with node:fs
// without giving a zero-dependency package node typings. `resolveJsonModule` is
// on, so static JSON imports typecheck cleanly and keep the leaf a leaf.
//
// It also makes the golden set EXPLICITLY enumerated: a new family that never
// reached this index fails the coverage assertion instead of being silently
// absent from the comparison.
const indexPath = join(GOLDEN_DIR, 'index.ts')
const names = [...corpus.map((family) => family.family), featureState.family].sort()
const ident = (name: string): string =>
  name.replace(/[^a-zA-Z0-9]+(.)?/g, (_m, c) => (c ? c.toUpperCase() : ''))
writeFileSync(
  indexPath,
  [
    '// GENERATED by scripts/update-wire-fixtures.ts — do not edit by hand.',
    '// Static imports rather than a filesystem read: packages/protocol is a leaf',
    '// package with `types: []`, so the fixture suite must not touch node:fs.',
    '',
    ...names.map((name) => `import ${ident(name)} from './${name}.json' with { type: 'json' }`),
    '',
    '/** Every committed golden family, keyed by family name. */',
    'export const GOLDEN: Record<string, unknown> = {',
    // Quote a key only when it is not a valid identifier ('browser-open'), so the
    // generated file is biome-clean AS WRITTEN. A generator whose output the
    // formatter wants to change makes every regeneration dirty the lint.
    ...names.map((name) =>
      /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)
        ? `  ${name}: ${ident(name)},`
        : `  '${name}': ${ident(name)},`,
    ),
    '}',
    '',
  ].join('\n'),
)

// Hand the output to the repo's own formatter rather than shipping 27 permanent
// format diagnostics. Biome's only quarrel with `JSON.stringify(x, null, 2)` is
// that it collapses a single-element array onto one line, which costs nothing:
// objects still print one field per line, so a diff still reads field-by-field
// and an added field is still a new line. Formatting here (instead of excluding
// the directory in biome.json) keeps the shared config untouched.
const formatted = Bun.spawnSync(['bunx', 'biome', 'format', '--write', GOLDEN_DIR], {
  cwd: join(import.meta.dirname, '..'),
  stdout: 'pipe',
  stderr: 'pipe',
})
if (formatted.exitCode !== 0) {
  console.error(new TextDecoder().decode(formatted.stderr))
  throw new Error('biome format failed on the generated golden corpus')
}

const cases =
  corpus.reduce((total, family) => total + family.cases.length, 0) + featureState.cases.length
console.log(`wrote ${corpus.length} families, ${cases} cases to ${GOLDEN_DIR}`)
