// GENERATED by scripts/update-wire-fixtures.ts — do not edit by hand.
// Static imports rather than a filesystem read: packages/protocol is a leaf
// package with `types: []`, so the fixture suite must not touch node:fs.

import approvals from './approvals.json' with { type: 'json' }
import automations from './automations.json' with { type: 'json' }
import browserOpen from './browser-open.json' with { type: 'json' }
import credentials from './credentials.json' with { type: 'json' }
import daemon from './daemon.json' with { type: 'json' }
import daemonHandshake from './daemon-handshake.json' with { type: 'json' }
import discovery from './discovery.json' with { type: 'json' }
import featureState from './feature-state.json' with { type: 'json' }
import files from './files.json' with { type: 'json' }
import handoff from './handoff.json' with { type: 'json' }
import harness from './harness.json' with { type: 'json' }
import headless from './headless.json' with { type: 'json' }
import host from './host.json' with { type: 'json' }
import inventory from './inventory.json' with { type: 'json' }
import issues from './issues.json' with { type: 'json' }
import maintenance from './maintenance.json' with { type: 'json' }
import model from './model.json' with { type: 'json' }
import perf from './perf.json' with { type: 'json' }
import runtimeState from './runtime-state.json' with { type: 'json' }
import search from './search.json' with { type: 'json' }
import server from './server.json' with { type: 'json' }
import sync from './sync.json' with { type: 'json' }
import terminal from './terminal.json' with { type: 'json' }
import transcript from './transcript.json' with { type: 'json' }
import workflows from './workflows.json' with { type: 'json' }
import workspace from './workspace.json' with { type: 'json' }

/** Every committed golden family, keyed by family name. */
export const GOLDEN: Record<string, unknown> = {
  approvals: approvals,
  automations: automations,
  'browser-open': browserOpen,
  credentials: credentials,
  daemon: daemon,
  'daemon-handshake': daemonHandshake,
  discovery: discovery,
  'feature-state': featureState,
  files: files,
  handoff: handoff,
  harness: harness,
  headless: headless,
  host: host,
  inventory: inventory,
  issues: issues,
  maintenance: maintenance,
  model: model,
  perf: perf,
  'runtime-state': runtimeState,
  search: search,
  server: server,
  sync: sync,
  terminal: terminal,
  transcript: transcript,
  workflows: workflows,
  workspace: workspace,
}
