/**
 * `@podium/commands` — L1 command CONTRACTS (ADR 3 D1). THE contract framework:
 * after POD-311 there is exactly one, and this package is it.
 *
 * Contracts only. Handlers register against these from their L3 feature modules
 * and are joined at the composition root; nothing here may import a service, a
 * database or an app.
 *
 * SCOPE NOTE (POD-728, CLOSED BY POD-311): this package landed with agent-mail as
 * its first tenant, leaving three things open. All three are now done: the issue
 * registry is migrated (`issues/`), and the live protocol contract sets are
 * ABSORBED rather than re-exported — `protocol/commands.ts` is `framework.ts`, and
 * the two session tables that depended on the framework (`session-commands.ts`,
 * `session-command-plane.ts`) came with it because they had to:
 * `@podium/commands` imports `@podium/protocol`, so a framework here with consumers
 * there would be a cycle. The speculative mutation envelope was later deleted:
 * production writes use the sync package's `OutboxCommand` contract.
 *
 * NO RE-EXPORT SHIMS were left behind in `@podium/protocol`. A shim would have made
 * the move invisible to every call site and would have added to the `reexport-shims`
 * ratchet the deletion audit counts — the opposite of absorbing a duplicate. Every
 * import site was repointed instead.
 */

export {
  ACCOUNT_CONTRACT_NAMES,
  ACCOUNT_CONTRACTS,
  AccountConnectInput,
  type AccountContractName,
  accountsConnectContract,
  accountsConnectInput,
  accountsDisconnectContract,
  accountsDisconnectInput,
  accountsLoginContract,
  accountsLoginInput,
} from './accounts/contracts'
export {
  APPROVAL_CONTRACT_NAMES,
  APPROVAL_CONTRACTS,
  type ApprovalContractName,
  approvalsApproveContract,
  approvalsApproveInput,
  approvalsDenyContract,
  approvalsDenyInput,
} from './approvals/contracts'
export {
  AUTOMATION_CONTRACT_NAMES,
  AUTOMATION_CONTRACTS,
  AUTOMATION_QUERY_NAMES,
  type AutomationCommandContract,
  type AutomationContractName,
  automationCreateContract,
  automationCreateInput,
  automationPatchInput,
  automationRemoveContract,
  automationRemoveInput,
  automationSetEnabledContract,
  automationSetEnabledInput,
  automationUpdateContract,
  automationUpdateInput,
} from './automations/contracts'
export {
  assertScheduleFloor,
  type CronSpec,
  isValidCron,
  MIN_SCHEDULE_INTERVAL_MS,
  minIntervalMs,
  nextAfter,
  nextRunAfter,
  parseCron,
  respectsScheduleFloor,
  SCHEDULE_FLOOR_MESSAGE,
} from './automations/cron'
export {
  CLOUD_CONTRACT_NAMES,
  CLOUD_CONTRACTS,
  type CloudContractName,
  cloudCreateAgentContract,
  cloudCreateAgentInput,
  cloudCreateMachineContract,
  cloudCreateMachineInput,
  cloudMoveSessionContract,
  cloudMoveSessionInput,
  cloudRepoInput,
  cloudRuntimeIdInput,
  cloudRuntimeSizeInput,
  cloudSourceSessionInput,
  cloudStopContract,
  cloudStopInput,
  cloudWakeContract,
  cloudWakeInput,
} from './cloud/contracts'
export {
  type AnyCommandContract,
  type AttributionPolicy,
  type AuthoredAttribution,
  CONTRACT_CONFLICT_CLASSES,
  type CommandAction,
  type CommandContract,
  type CommandContractBase,
  type CommandPolicy,
  type CommandResource,
  type ConfirmationRule,
  type ContractConflictClass,
  type ContractInput,
  type CreationOwnership,
  classificationErrors,
  type DeliveryClass,
  type DeliveryPolicy,
  type ErrorConsistency,
  type MachineVerb,
  type OptimisticEffect,
  type OptimisticReducer,
  type RedactionPolicy,
  type RoleFloor,
  registryClassificationErrors,
  SERVED_NOWHERE,
  type TransportTag,
  type VisibilityClass,
} from './contract'
export {
  CONVERSATION_CONTRACT_NAMES,
  CONVERSATION_CONTRACTS,
  type ConversationContractName,
  conversationsSetMetaContract,
  conversationsSetMetaInput,
} from './conversations/contracts'
export {
  FILE_CONTRACT_NAMES,
  FILE_CONTRACTS,
  type FileContractName,
  filesWriteContract,
  filesWriteInput,
} from './files/contracts'
export {
  discoveryRefreshReposContract,
  discoveryRefreshReposInput,
  discoveryScanFolderContract,
  discoveryScanFolderInput,
  discoveryScanMachineContract,
  discoveryScanMachineInput,
  FLEET_COMMAND_NAMES,
  FLEET_CONTRACT_LIST,
  FLEET_CONTRACTS,
  type FleetCommandContract,
  type FleetContractName,
  type FleetServerRole,
  fleetServerRoleOf,
  machineAdoptContract,
  machineAdoptInput,
  machinePairingCodeContract,
  machinePairingCodeInput,
  machineRenameContract,
  machineRenameInput,
  machineRevokeContract,
  machineRevokeInput,
  machineShareContract,
  machineShareInput,
  machineTransferOwnershipContract,
  machineTransferOwnershipInput,
  machineTransferServerContract,
  machineTransferServerInput,
  machineUnshareContract,
  machineUnshareInput,
  repoAddContract,
  repoAddInput,
  repoAddManyContract,
  repoAddManyInput,
  repoRemoveContract,
  repoRemoveInput,
  repoSetPrefixContract,
  repoSetPrefixInput,
} from './fleet/contracts'
export {
  type CommandDef,
  type CommandInput,
  type CommandName,
  type CommandOutput,
  type CommandRedaction,
  type CommandScope,
  type CommandTransport,
  type ConflictClass,
  commandExposure,
  commandVisibility,
  defineCommands,
  isExposedOn,
  LOCK_COMMAND_NAMES,
  type LockCommandName,
  type OfflineClass,
  type PolicyResource,
  type PolicyScope,
} from './framework'
export {
  HOST_CONTRACT_NAMES,
  HOST_CONTRACTS,
  type HostContractName,
  hostsMemoryBreakdownContract,
  hostsMemoryBreakdownInput,
} from './hosts/contracts'
export {
  AUTH_CONTRACT_NAMES,
  AUTH_CONTRACTS,
  type AuthContractName,
  authSetLoginRequiredContract,
  authSetLoginRequiredInput,
  authSetPasswordContract,
  authSetPasswordInput,
  SETUP_CONTRACT_NAMES,
  SETUP_CONTRACTS,
  type SetupContractName,
  setupCompleteContract,
  setupCompleteInput,
  setupConnectContract,
  setupConnectInput,
  setupJoinContract,
  setupJoinInput,
  setupSetChannelContract,
  setupSetChannelInput,
  TELEMETRY_CONTRACT_NAMES,
  TELEMETRY_CONTRACTS,
  type TelemetryContractName,
  telemetryResetIdContract,
  telemetryResetIdInput,
  telemetrySetContract,
  telemetrySetInput,
} from './instance/contracts'
export {
  ADDITIVE_POLICY,
  CREATES_NOTHING,
  ISSUE_ATTRIBUTION,
  ISSUE_REDACTION,
  ISSUE_VISIBILITY,
  MANAGE_POLICY,
  PER_USER_DELIVERY,
  PER_USER_POLICY,
  PER_USER_VISIBILITY,
  READ_DELIVERY,
  READ_POLICY,
  SERVED_EVERYWHERE,
  SERVED_ON_WIRE,
  TARGETED_ERRORS,
  UNTARGETED_ERRORS,
  WRITE_DELIVERY,
  WRITE_POLICY,
} from './issues/cells'
export {
  ISSUE_COMMAND_NAMES,
  ISSUE_CONTRACT_LIST,
  ISSUE_CONTRACTS,
  type IssueContractName,
} from './issues/contracts'
export {
  LAYOUT_CONTRACT_NAMES,
  LAYOUT_CONTRACTS,
  type LayoutClearInput,
  type LayoutContractName,
  type LayoutSetInput,
  layoutClearContract,
  layoutClearInput,
  layoutSetContract,
  layoutSetInput,
} from './layout/contracts'
export {
  type AddressDeps,
  type AddressResolution,
  type HumanCeiling,
  type PlacementDecision,
  type PlacementDeps,
  placementDecision,
  resolveAddress,
  SINGLE_USER_CEILING,
  UNADDRESSABLE,
} from './mail/ceiling'
export {
  awaitAgentContract,
  awaitAgentInput,
  MAIL_CONTRACTS,
  type MailContractName,
  mailAskContract,
  mailAskInput,
  mailDismissContract,
  mailDismissInput,
  mailInboxConsumeContract,
  mailInboxInput,
  mailLedgerContract,
  mailLedgerInput,
  mailPendingRemindersContract,
  mailPendingRemindersInput,
  mailReplyContract,
  mailReplyInput,
  mailSendContract,
  mailSendInput,
  mailShowContract,
  mailShowInput,
  mailStatusContract,
  mailStatusInput,
  spawnAgentContract,
  spawnAgentInput,
} from './mail/contracts'
export {
  deliversUnwrapped,
  exemptFromBrakes,
  isHumanPrincipal,
  type MailSenderPrincipal,
  operatorAddressee,
  senderBrakeKey,
  senderLabel,
} from './mail/principal'
export {
  MODEL_CONTRACT_NAMES,
  MODEL_CONTRACTS,
  type ModelContractName,
  modelsRefreshContract,
  modelsRefreshInput,
} from './models/contracts'
export {
  PERF_CONTRACT_NAMES,
  PERF_CONTRACTS,
  type PerfContractName,
  perfReportContract,
  perfReportInput,
  perfResetContract,
  perfResetInput,
} from './perf/contracts'
export {
  READ_POSITION_CONTRACT_NAMES,
  READ_POSITION_CONTRACTS,
  type ReadPositionAdvanceInput,
  type ReadPositionContractName,
  readPositionAdvanceContract,
  readPositionAdvanceInput,
} from './read-position/contracts'
export {
  applyRedaction,
  applyRedactionWithReport,
  messageMentionsRedactedValue,
  REDACTED,
  type RedactionReport,
  type RedactionSide,
  redactForLog,
  redactReport,
  redactUnknownForLog,
} from './redaction'
export * from './sessions/command-plane'
export {
  EXPORTABLE_HARNESSES,
  type SessionHandoffInput,
  type SessionHandoffOutput,
  sessionHandoffContract,
  sessionHandoffInput,
  sessionHandoffOutput,
} from './sessions/handoff'
export {
  RENAME_REJECTIONS,
  type SessionRenameInput,
  type SessionRenameOutcome,
  sessionRenameContract,
  sessionRenameInput,
  sessionRenameReducer,
} from './sessions/rename'
export * from './sessions/session-state-commands'
export {
  CONTRACT_TIER,
  contractMatrixRow,
  preferencePathsInTier,
  SECRET_COMMAND_KEYS,
  SETTINGS_COMMAND_NAMES,
  SETTINGS_CONTRACTS,
  type SettingsContractName,
  settingsClearSecretContract,
  settingsClearSecretInput,
  settingsSetSecretContract,
  settingsSetSecretInput,
  settingsTelegramSetupPollContract,
  settingsTelegramSetupPollInput,
  settingsTelegramSetupStartContract,
  settingsTelegramSetupStartInput,
  settingsUpdateInstanceContract,
  settingsUpdateInstanceInput,
  settingsUpdatePersonalContract,
  settingsUpdatePersonalInput,
  TIER_COMMAND,
  WRITABLE_PREFERENCE_PATHS,
} from './settings/contracts'
export {
  applySettingsPatch,
  type ChangedLeaf,
  changedSettingsLeaves,
  ONLINE_ONLY_SETTINGS_COMMANDS,
  type PlanOptions,
  planSettingsWrite,
  readSettingsLeaf,
  type SettingsWriteIntent,
  type SettingsWritePlan,
  type SettingsWriteRefusal,
} from './settings/write-plan'
export {
  SPEC_CONTRACT_NAMES,
  SPEC_CONTRACTS,
  type SpecContractName,
  SpecStatus,
  specsCreateContract,
  specsCreateInput,
  specsRemoveContract,
  specsRemoveInput,
  specsSaveContract,
  specsSaveInput,
} from './specs/contracts'
export {
  SUPERAGENT_COMMAND_NAMES,
  SUPERAGENT_CONTRACTS,
  type SuperagentContractName,
  type SuperagentUserFocus,
  superagentClearContract,
  superagentClearInput,
  superagentConciergeContract,
  superagentConciergeInput,
  superagentInterruptTurnContract,
  superagentInterruptTurnInput,
  superagentOpenInTerminalContract,
  superagentOpenInTerminalInput,
  superagentRestartContract,
  superagentRestartInput,
  superagentSendTurnContract,
  superagentSendTurnInput,
  superagentStartBtwContract,
  superagentStartBtwInput,
  superagentUserFocus,
} from './superagent/contracts'
export {
  WORKFLOW_ADVANCE_NAMES,
  WORKFLOW_CONTRACTS,
  type WorkflowCommandContract,
  type WorkflowContractName,
  workflowAdoptContract,
  workflowAdoptInput,
  workflowAdvanceOf,
  workflowAssignContract,
  workflowAssignInput,
  workflowAssignStepContract,
  workflowAssignStepInput,
  workflowCheckpointContract,
  workflowCheckpointInput,
  workflowCreateContract,
  workflowCreateInput,
  workflowForkContract,
  workflowForkInput,
  workflowProfileSaveContract,
  workflowProfileSaveInput,
  workflowPublishContract,
  workflowPublishInput,
  workflowRetryContract,
  workflowRetryInput,
  workflowReviseContract,
  workflowReviseInput,
  workflowSkipContract,
  workflowSkipInput,
} from './workflows/contracts'
export {
  type AdvanceDeliveryIdentity,
  type AdvanceIdempotencyPort,
  AMBIGUOUS_ADVANCE_MESSAGE,
  advanceIdempotencyKey,
  assertAdvanceIsDeliverable,
  type WorkflowAdvanceIdempotency,
} from './workflows/idempotency'
export {
  canReadWorkflowEntity,
  SINGLE_USER_HUMAN,
  SINGLE_USER_WORKFLOW_OWNERSHIP,
  type WorkflowDecision,
  type WorkflowEntityKind,
  type WorkflowEntityRef,
  type WorkflowOwnershipPort,
  type WorkflowPrincipal,
  type WorkflowUserRef,
  type WorkflowVerb,
  workflowDecision,
} from './workflows/ownership'
