/**
 * Drive the REAL legacy replica writer and hand back everything it persisted.
 *
 * This is the capture half of POD-377's "tested from a captured real replica
 * snapshot" criterion. It lives in `packages/client-core` because that is where the
 * writer lives, and it is a module rather than a test so two consumers can share
 * one definition of "what the writer produces": `scripts/capture-legacy-replica-snapshot.ts`
 * writes the fixture, and `legacy-snapshot.test.ts` fails when the writer drifts
 * away from the fixture that was written.
 *
 * WHY A SHARED MODULE AND NOT TWO COPIES. A fixture regenerated by one code path and
 * verified by another is a fixture verified against nothing in particular — the two
 * paths drift and the drift guard reports on a store neither the app nor the
 * migration ever sees. One function, two callers.
 *
 * WHAT IS EXERCISED, and why each one is here rather than "for completeness":
 *
 *   ENTITY COLLECTIONS — the rows the migration must DISCARD. Present so the
 *     discard is observed happening to real data rather than to an empty store.
 *   THE CURSOR — a bare integer, which ADR 2 D1 says is not a cursor. Present so
 *     `cursorDiscarded` is exercised against a cursor that genuinely exists.
 *   THE OUTBOX, in all three homes — the pre-replica standalone blob, the queued
 *     collection, and the awaiting-truth collection. This is the family POD-377's
 *     decision is about; a capture without queued entries would test the easy half.
 *     The awaiting-truth entry must import as `accepted` rather than `queued`,
 *     because re-sending an accepted mutation is the bug that split the two homes.
 *   UI STATE — ADR 6 D7 preferences, which must be LEFT BEHIND. Present so "the
 *     migration did not delete the user's layout" is a measured claim.
 */

import type { IssueWire, SessionMeta, TranscriptItem } from '@podium/model'
import { createReplica } from './replica'

/**
 * The recognisable payload every queued entry in the capture carries.
 *
 * Exported so the migration's tests can assert PRESENCE (an adopted entry kept the
 * user's text) and ABSENCE (a parked entry did not carry one user's text into
 * another user's recovery UI) by searching for the same string, rather than each
 * test agreeing separately about what the payload was supposed to look like.
 */
export const MIGRATION_PROBE_TEXT = 'the-users-own-words'

/** The whole key-value store, as the writer left it. */
export type LegacyReplicaSnapshot = Record<string, string>

/**
 * TWO DEVICES, because one store cannot show both shapes and the difference is not
 * cosmetic.
 *
 * The first attempt at this capture seeded the pre-replica `podium.outbox.v1` blob
 * and then drove the current writer over it, expecting a store with all three
 * outbox homes at once. The entry VANISHED — and that is correct behaviour, not a
 * capture bug: the shipping replica migrates the standalone blob into its outbox
 * collection and deletes the key on first use. A device that has run any recent
 * build therefore CANNOT have both, and a fixture that showed both would be a shape
 * no user has ever had.
 *
 * So the capture records the two populations that actually exist:
 *
 *   `collections` — a device on a recent build. The ancient blob has already been
 *     folded in, so its entry appears inside the outbox collection and the
 *     standalone key is gone.
 *   `preReplica` — a device that upgraded from a build OLDER than the replica
 *     collections. It has the standalone JSON ARRAY and nothing else, which is a
 *     different decode path in `readLegacyReplica` and the one that would rot
 *     unnoticed, because no current writer can produce it.
 */
export interface CapturedLegacyReplicas {
  readonly collections: LegacyReplicaSnapshot
  readonly preReplica: LegacyReplicaSnapshot
}

/** A row shaped like the collection it goes into; only the id is load-bearing. */
const row = (id: string): never => ({ id, sessionId: id, title: id }) as unknown as never

/**
 * Produce a legacy store and return every key the writer wrote.
 *
 * The content is deliberately recognisable — `MIGRATION_PROBE_TEXT` below — so a
 * test can assert that a payload did or did not survive a code path by looking for
 * it, rather than by trusting a shape.
 */
export async function captureLegacyReplicaSnapshot(): Promise<CapturedLegacyReplicas> {
  return {
    collections: await captureCollectionsDevice(),
    preReplica: PRE_REPLICA_DEVICE,
  }
}

/**
 * The pre-replica device: one plain JSON ARRAY under the standalone key, and
 * nothing else.
 *
 * Written as a literal rather than captured, and that is the honest label: the
 * writer that produced this shape (`OUTBOX_LS_KEY` in `../outbox.ts`, before the
 * replica collections existed) is gone from the tree, so there is nothing left to
 * drive. It is here because such devices are still out there and the decode path
 * for them is live code — a fixture nobody can regenerate is still better than a
 * branch nobody exercises.
 */
const PRE_REPLICA_DEVICE: LegacyReplicaSnapshot = {
  'podium.outbox.v1': JSON.stringify([
    {
      mutationId: 'mut_ancient',
      kind: 'sessions.rename',
      input: { title: `${MIGRATION_PROBE_TEXT} (ancient)` },
      queuedAt: 5,
    },
  ]),
}

async function captureCollectionsDevice(): Promise<LegacyReplicaSnapshot> {
  const data = new Map<string, string>(Object.entries(PRE_REPLICA_DEVICE))
  const storage = {
    getItem: (k: string) => data.get(k) ?? null,
    setItem: (k: string, v: string) => void data.set(k, v),
    removeItem: (k: string) => void data.delete(k),
  }

  // Seeded with the ancient blob so the capture goes through the replica's OWN
  // one-time fold of it: the entry ends up inside the outbox collection and the
  // standalone key is deleted, which is what a real recent device looks like.
  const replica = createReplica({ storage, enumerateKeys: () => [...data.keys()] })

  replica.applySnapshot('sessions', [
    { sessionId: 'sess_1', title: 'a session', agentKind: 'claude-code' } as unknown as SessionMeta,
  ])
  replica.applySnapshot('issues', [{ id: 'iss_1', title: 'an issue' } as unknown as IssueWire])
  replica.applySnapshot('conversations', [row('conv_1')])
  replica.applySnapshot('automations', [row('auto_1')])
  replica.applySnapshot('automationRuns', [row('run_1')])
  replica.putTranscriptWindow('conv_1', [
    { id: 'i1', role: 'user', text: 'a transcript line' } as unknown as TranscriptItem,
  ])

  replica.setCursor(4211)

  // MERGE rather than replace. `save()` has snapshot semantics, so passing only
  // the new entries would delete the ancient one the fold just brought in — which
  // is exactly what the first version of this capture did, silently producing a
  // fixture with no pre-replica entry in it at all.
  const queued = replica.outboxStorage()
  queued.save([
    ...queued.load(),
    {
      mutationId: 'mut_queued_1',
      kind: 'sessions.rename',
      input: { title: `${MIGRATION_PROBE_TEXT} (queued first)` },
      queuedAt: 10,
    },
    {
      mutationId: 'mut_queued_2',
      kind: 'issues.close',
      input: { id: 'iss_1', note: `${MIGRATION_PROBE_TEXT} (queued second)` },
      queuedAt: 20,
    },
  ])
  replica.outboxAwaitingStorage().save([
    {
      mutationId: 'mut_awaiting',
      kind: 'sessions.rename',
      input: { title: `${MIGRATION_PROBE_TEXT} (awaiting truth)` },
      queuedAt: 15,
      state: 'awaiting-truth',
    },
  ])

  replica.uiState().set('podium.view', 'home')

  // The cursor write is FENCED behind the entity writes issued before it — the
  // cursor-after-data invariant, implemented as a promise chain — so it lands a
  // few microtasks after the call returns. Drained rather than slept on: a fixed
  // timeout before an assertion is a flake in this lane.
  for (let i = 0; i < 50; i += 1) await Promise.resolve()

  return Object.fromEntries([...data.entries()].sort(([a], [b]) => (a < b ? -1 : 1)))
}
