/** Workspace read scope retired by POD-5437; other lanes keep their switches. */
export const WORKSPACE_READER_FILES = [
  'apps/web/src/components/IssueReference.tsx',
  'apps/web/src/components/RefMiniview.tsx',
  'apps/web/src/components/PodiumLinkHost.tsx',
  'apps/web/src/lib/pane-data-layer.ts',
  'apps/web/src/lib/sidebar-data-layer.ts',
  'apps/web/src/lib/chips-data-layer.ts',
  'apps/web/src/lib/header-data-layer.ts',
  'apps/web/src/app/store-worklist-pool.ts',
  'apps/web/src/app/mission-pane-pool-screen.ts',
  'apps/web/src/app/FlightDeck.tsx',
  'apps/web/src/app/AppShell.tsx',
  'apps/web/src/app/pool-screens.ts',
  'apps/web/src/app/header-data.ts',
  'apps/web/src/app/shell-pool-screen.ts',
  'apps/web/src/app/MachinesPanel.tsx',
  'apps/web/src/app/FoldedFlightDeckBar.tsx',
  'apps/web/src/app/workspace-mission.ts',
  'apps/web/src/app/workspace-mission-reads.ts',
  'apps/web/src/app/RightRail.tsx',
  'apps/web/src/app/AgentConcurrencyHistory.tsx',
  'apps/web/src/app/shell-data.ts',
  'apps/web/src/app/pane-pool-screen.ts',
  'apps/web/src/features/terminal/session-pane-pool-screen.ts',
  'apps/web/src/features/terminal/AgentPanel.tsx',
  'apps/web/src/features/terminal/use-session-pane-inputs.ts',
  'apps/web/src/features/terminal/session-pane-data-layer.ts',
  'apps/web/src/features/machines/ConnectionIndicator.tsx',
  'apps/web/src/features/machines/LoadPanel.tsx',
  'apps/web/src/features/machines/host-lifecycle-settings.ts',
  'apps/web/src/features/machines/HostIndicators.tsx',
  'apps/web/src/features/machines/QuotaIndicator.tsx',
  'apps/web/src/features/mobile-handoff/mobile-handoff.ts',
  'apps/web/src/features/issues/board-pool-row.tsx',
  'apps/web/src/features/issues/IssuePage.tsx',
  'apps/web/src/features/issues/board-pool-data.ts',
  'apps/web/src/features/issues/board-data-layer.ts',
  'apps/web/src/features/issues/IssuePanelView.tsx',
  'apps/web/src/features/worklist/SidebarUnified.tsx',
  'apps/web/src/features/worklist/use-sidebar-projects.ts',
  'apps/web/src/features/worklist/SidebarRail.tsx',
  'apps/web/src/features/chat/IssueChipLiveness.tsx',
  'apps/web/src/features/issues/issue-page/pool-screen.ts',
  'apps/web/src/features/issues/explorer/explorer-context.tsx',
  'apps/web/src/features/issues/explorer/IssueExplorerList.tsx',
  'apps/web/src/features/issues/explorer/explorer-pool-data.ts',
  'apps/web/src/app/StatusStrip.tsx',
  'apps/web/src/app/TopBar.tsx',
  'apps/web/src/features/issues/issue-page/issue-page-data.tsx',
  'apps/web/src/features/issues/issue-page-model.ts',
  'apps/web/src/features/issues/issue-lifecycle.tsx',
] as const

export const LEGACY_READER_PATTERN =
  /\b(?:useLegacy\w+|Legacy(?:Sidebar\w*|FlightDeck|MissionAgentMenu|Issue\w*|Ref\w*|Header\w*))\b/g
export const RETIRED_DISPATCH_PATTERN =
  /\b(?:sidebar|header|chips|pane|missionPane|sessionPane|issuePage|issueBoard|shell)(?:DataLayer|CheckRequested)\s*\(/g
